In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

from urllib.request import urlopen
from bs4 import BeautifulSoup
import re

In [2]:
url ="https://www.hubertiming.com/results/2018MLK"   # open link
html =urlopen(url)

In [3]:
soup = BeautifulSoup(html)

In [4]:
title = soup.title
print(title)
print(title.text)

<title>Race results for the 2018 MLK Dream Run!</title>
Race results for the 2018 MLK Dream Run!

In [5]:
links = soup.find_all("a")
print(links)

[<a href="https://www.mlkdreamrun.com/" target="_blank">MLK Dream Run</a>, <a href="mailto:timing@hubertiming.com">timing@hubertiming.com</a>, <a href="https://www.hubertiming.com">Huber Timing Home</a>, <a class="btn btn-primary btn-lg" href="/results/2018MLK10K" role="button" style="margin: 0px 0px 5px 5px"><i aria-hidden="true" class="fa fa-user"></i> 10K</a>, <a class="btn btn-primary btn-lg" href="/results/2018MLK15K" role="button" style="margin: 0px 0px 5px 5px"><i aria-hidden="true" class="fa fa-user"></i> 15K</a>, <a class="btn btn-primary btn-lg" href="/results/summary/2018MLK" role="button" style="margin: 0px 0px 5px 5px"><i class="fa fa-stream"></i> Summary</a>, <a id="individual" name="individual"></a>, <a data-url="/results/2018MLK" href="#tabs-1" id="rootTab" style="font-size: 18px">5K Results</a>, <a href="https://www.hubertiming.com/"><img height="65" src="https://www.hubertiming.com//sites/all/themes/hubertiming/images/clockWithFinishSign_small.png" width="50"/>Huber Timing</a>, <a href="https://facebook.com/hubertiming/"><img src="https://www.hubertiming.com/results/FB-f-Logo__blue_50.png"/></a>, <a class="small" id="bestFeatureEver" style="color:#007bff">Dark Mode</a>]

In [6]:
# or
links = soup.find_all("a", href = True)
for link in links:
    print(link["href"])

https://www.mlkdreamrun.com/
mailto:timing@hubertiming.com
https://www.hubertiming.com
/results/2018MLK10K
/results/2018MLK15K
/results/summary/2018MLK
#tabs-1
https://www.hubertiming.com/
https://facebook.com/hubertiming/

In [7]:
allrows =soup.find_all("tr")
print(allrows)

[<tr colspan="2">
<b>5K:</b>
</tr>, <tr>
<td>Finishers:</td>
<td>191</td>
</tr>, <tr>
<td>Male:</td>
<td>78</td>
</tr>, <tr>
<td>Female:</td>
<td>113</td>
</tr>, <tr class="header">
<th>Place</th>
<th>Bib</th>
<th>Name</th>
<th>Gender</th>
<th>Age</th>
<th>City</th>
<th>State</th>
<th>Chip Pace</th>
<th>Time</th>
<th>Gender Place</th>
<th>Age Group</th>
<th>Age Group Place</th>
<th>Time to Start</th>
<th>Gun Time</th>
</tr>, <tr data-bib="1191">
<td>1</td>
<td>1191</td>
<td>

                    MAX RANDOLPH

                </td>
<td>M</td>
<td>29</td>
<td>WASHINGTON</td>
<td>DC</td>
<td>5:25</td>
<td>16:48</td>
<td>

                    1 of 78

                </td>
<td>M 21-39</td>
<td>

                    1 of 33

                </td>
<td>0:08</td>
<td>16:56</td>
</tr>, <tr data-bib="1080">
<td>2</td>
<td>1080</td>
<td>

                    NEED NAME KAISER RUNNER

                </td>
<td>M</td>
<td>25</td>
<td>PORTLAND</td>
<td>OR</td>
<td>5:39</td>
<td>17:31</td>
<td>

                    2 of 78

                </td>
<td>M 21-39</td>
<td>

                    2 of 33

                </td>
<td>0:09</td>
<td>17:40</td>
</tr>, <tr data-bib="1275">
<td>3</td>
<td>1275</td>
<td>

                    DAN FRANEK

                </td>
<td>M</td>
<td>52</td>
<td>PORTLAND</td>
<td>OR</td>
<td>5:53</td>
<td>18:15</td>
<td>

                    3 of 78

                </td>
<td>M 40-54</td>
<td>

                    1 of 27

                </td>
<td>0:07</td>
<td>18:22</td>
</tr>, <tr data-bib="1223">
<td>4</td>
<td>1223</td>
<td>

                    PAUL TAYLOR

                </td>
<td>M</td>
<td>54</td>
<td>PORTLAND</td>
<td>OR</td>
<td>5:58</td>
<td>18:31</td>
<td>

                    4 of 78

                </td>
<td>M 40-54</td>
<td>

                    2 of 27

                </td>
<td>0:07</td>
<td>18:38</td>
</tr>, <tr data-bib="1245">
<td>5</td>
<td>1245</td>
<td>

                    THEO KINMAN

                </td>
<td>M</td>
<td>22</td>
<td></td>
<td></td>
<td>6:17</td>
<td>19:31</td>
<td>

                    5 of 78

                </td>
<td>M 21-39</td>
<td>

                    3 of 33

                </td>
<td>0:09</td>
<td>19:40</td>
</tr>, <tr data-bib="1185">
<td>6</td>
<td>1185</td>
<td>

                    MELISSA GIRGIS

                </td>
<td>F</td>
<td>27</td>
<td>PORTLAND</td>
<td>OR</td>
<td>6:20</td>
<td>19:39</td>
<td>

                    1 of 113

                </td>
<td>F 21-39</td>
<td>

                    1 of 53

                </td>
<td>0:07</td>
<td>19:46</td>
</tr>, <tr data-bib="1251">
<td>7</td>
<td>1251</td>
<td>

                    CHARLIE COGGESHALL

                </td>
<td>M</td>
<td>39</td>
<td>PORTLAND</td>
<td>OR</td>
<td>6:24</td>
<td>19:51</td>
<td>

                    6 of 78

                </td>
<td>M 21-39</td>
<td>

                    4 of 33

                </td>
<td>0:10</td>
<td>20:01</td>
</tr>, <tr data-bib="1154">
<td>8</td>
<td>1154</td>
<td>

                    UNKNOWN RUNNER SEE TIMER

                </td>
<td>M</td>
<td></td>
<td></td>
<td></td>
<td>8:03</td>
<td>24:58</td>
<td>

                    7 of 78

                </td>
<td></td>
<td>

                    1 of 9

                </td>
<td>2:00</td>
<td>26:58</td>
</tr>, <tr data-bib="1163">
<td>9</td>
<td>1163</td>
<td>

                    UNKNOWN RUNNER SEE TIMER

                </td>
<td>M</td>
<td></td>
<td></td>
<td></td>
<td>8:04</td>
<td>25:01</td>
<td>

                    8 of 78

                </td>
<td></td>
<td>

                    2 of 9

                </td>
<td>1:59</td>
<td>27:00</td>
</tr>, <tr data-bib="1242">
<td>10</td>
<td>1242</td>
<td>

                    KIMONTI WILSON

                </td>
<td>F</td>
<td>48</td>
<td></td>
<td></td>
<td>8:04</td>
<td>25:01</td>
<td>

                    2 of 113

                </td>
<td>F 40-54</td>
<td>

                    1 of 37

                </td>
<td>1:59</td>
<td>27:00</td>
</tr>, <tr data-bib="1017">
<td>11</td>
<td>1017</td>
<td>

                    COREY MCMANUS

                </td>
<td>M</td>
<td>37</td>
<td>BEAVERTON</td>
<td>OR</td>
<td>8:09</td>
<td>25:17</td>
<td>

                    9 of 78

                </td>
<td>M 21-39</td>
<td>

                    5 of 33

                </td>
<td>0:22</td>
<td>25:39</td>
</tr>, <tr data-bib="1112">
<td>12</td>
<td>1112</td>
<td>

                    MITCHELL JOHNSON

                </td>
<td>M</td>
<td>25</td>
<td>PORTLAND</td>
<td>OR</td>
<td>8:13</td>
<td>25:31</td>
<td>

                    10 of 78

                </td>
<td>M 21-39</td>
<td>

                    6 of 33

                </td>
<td>0:15</td>
<td>25:46</td>
</tr>, <tr data-bib="1062">
<td>13</td>
<td>1062</td>
<td>

                    ALEX KABA

                </td>
<td>M</td>
<td>36</td>
<td>PORTLAND</td>
<td>OR</td>
<td>8:14</td>
<td>25:31</td>
<td>

                    11 of 78

                </td>
<td>M 21-39</td>
<td>

                    7 of 33

                </td>
<td>0:14</td>
<td>25:45</td>
</tr>, <tr data-bib="1227">
<td>14</td>
<td>1227</td>
<td>

                    ROBYN MCGILLIS

                </td>
<td>F</td>
<td>44</td>
<td>PORTLAND</td>
<td>OR</td>
<td>8:18</td>
<td>25:44</td>
<td>

                    3 of 113

                </td>
<td>F 40-54</td>
<td>

                    2 of 37

                </td>
<td>0:08</td>
<td>25:52</td>
</tr>, <tr data-bib="1067">
<td>15</td>
<td>1067</td>
<td>

                    MITCHELL WARDEN

                </td>
<td>M</td>
<td>29</td>
<td>PORTLAND</td>
<td>OR</td>
<td>8:19</td>
<td>25:46</td>
<td>

                    12 of 78

                </td>
<td>M 21-39</td>
<td>

                    8 of 33

                </td>
<td>0:14</td>
<td>26:00</td>
</tr>, <tr data-bib="1136">
<td>16</td>
<td>1136</td>
<td>

                    JULIA METZ

                </td>
<td>F</td>
<td>32</td>
<td>PORTLAND</td>
<td>OR</td>
<td>8:33</td>
<td>26:31</td>
<td>

                    4 of 113

                </td>
<td>F 21-39</td>
<td>

                    2 of 53

                </td>
<td>0:33</td>
<td>27:04</td>
</tr>, <tr data-bib="1199">
<td>17</td>
<td>1199</td>
<td>

                    JEREMY AREZZINI

                </td>
<td>M</td>
<td>38</td>
<td>LAKE OSWEGO</td>
<td>OR</td>
<td>8:37</td>
<td>26:44</td>
<td>

                    13 of 78

                </td>
<td>M 21-39</td>
<td>

                    9 of 33

                </td>
<td>0:41</td>
<td>27:25</td>
</tr>, <tr data-bib="1252">
<td>18</td>
<td>1252</td>
<td>

                    ETHAN POWELL

                </td>
<td>M</td>
<td></td>
<td></td>
<td></td>
<td>8:40</td>
<td>26:52</td>
<td>

                    14 of 78

                </td>
<td></td>
<td>

                    3 of 9

                </td>
<td>0:11</td>
<td>27:03</td>
</tr>, <tr data-bib="1231">
<td>19</td>
<td>1231</td>
<td>

                    TIMOTHY KEARNEY

                </td>
<td>M</td>
<td>42</td>
<td>PORTLAND</td>
<td>OR</td>
<td>8:42</td>
<td>26:58</td>
<td>

                    15 of 78

                </td>
<td>M 40-54</td>
<td>

                    3 of 27

                </td>
<td>0:11</td>
<td>27:09</td>
</tr>, <tr data-bib="1108">
<td>20</td>
<td>1108</td>
<td>

                    TIMOTHY RINGERING

                </td>
<td>M</td>
<td>50</td>
<td>VANCOUVER</td>
<td>WA</td>
<td>8:43</td>
<td>27:02</td>
<td>

                    16 of 78

                </td>
<td>M 40-54</td>
<td>

                    4 of 27

                </td>
<td>0:10</td>
<td>27:12</td>
</tr>, <tr data-bib="1118">
<td>21</td>
<td>1118</td>
<td>

                    PONTUS JADERHOLM

                </td>
<td>M</td>
<td>43</td>
<td>PORTLAND</td>
<td>OR</td>
<td>8:45</td>
<td>27:08</td>
<td>

                    17 of 78

                </td>
<td>M 40-54</td>
<td>

                    5 of 27

                </td>
<td>0:13</td>
<td>27:21</td>
</tr>, <tr data-bib="1246">
<td>22</td>
<td>1246</td>
<td>

                    KERRY FLAGG

                </td>
<td>M</td>
<td></td>
<td></td>
<td></td>
<td>8:45</td>
<td>27:10</td>
<td>

                    18 of 78

                </td>
<td></td>
<td>

                    4 of 9

                </td>
<td>0:10</td>
<td>27:20</td>
</tr>, <tr data-bib="1244">
<td>23</td>
<td>1244</td>
<td>

                    JARRED FLAGG

                </td>
<td>M</td>
<td></td>
<td></td>
<td></td>
<td>8:46</td>
<td>27:11</td>
<td>

                    19 of 78

                </td>
<td></td>
<td>

                    5 of 9

                </td>
<td>0:10</td>
<td>27:21</td>
</tr>, <tr data-bib="1224">
<td>24</td>
<td>1224</td>
<td>

                    KEN SKEEN

                </td>
<td>M</td>
<td>57</td>
<td>PORTLAND</td>
<td>OR</td>
<td>8:46</td>
<td>27:12</td>
<td>

                    20 of 78

                </td>
<td>M 55+</td>
<td>

                    1 of 5

                </td>
<td>0:18</td>
<td>27:30</td>
</tr>, <tr data-bib="1065">
<td>25</td>
<td>1065</td>
<td>

                    SARA KOPTON

                </td>
<td>F</td>
<td>40</td>
<td>PORTLAND</td>
<td>OR</td>
<td>8:51</td>
<td>27:27</td>
<td>

                    5 of 113

                </td>
<td>F 40-54</td>
<td>

                    3 of 37

                </td>
<td>0:20</td>
<td>27:47</td>
</tr>, <tr data-bib="1274">
<td>26</td>
<td>1274</td>
<td>

                    KAISER GUEST

                </td>
<td>F</td>
<td>40</td>
<td>PORTLAND</td>
<td>OR</td>
<td>8:54</td>
<td>27:37</td>
<td>

                    6 of 113

                </td>
<td>F 40-54</td>
<td>

                    4 of 37

                </td>
<td>0:09</td>
<td>27:46</td>
</tr>, <tr data-bib="1208">
<td>27</td>
<td>1208</td>
<td>

                    JUSTIN PERZ

                </td>
<td>M</td>
<td>33</td>
<td>PORTLAND</td>
<td>OR</td>
<td>8:55</td>
<td>27:39</td>
<td>

                    21 of 78

                </td>
<td>M 21-39</td>
<td>

                    10 of 33

                </td>
<td>0:38</td>
<td>28:17</td>
</tr>, <tr data-bib="1072">
<td>28</td>
<td>1072</td>
<td>

                    ESTELA SÁNCHEZ

                </td>
<td>F</td>
<td>41</td>
<td>PORTLAND</td>
<td>OR</td>
<td>8:57</td>
<td>27:45</td>
<td>

                    7 of 113

                </td>
<td>F 40-54</td>
<td>

                    5 of 37

                </td>
<td>0:08</td>
<td>27:53</td>
</tr>, <tr data-bib="1018">
<td>29</td>
<td>1018</td>
<td>

                    JASON WILLIAMS

                </td>
<td>M</td>
<td>41</td>
<td>PORTLAND</td>
<td>OR</td>
<td>8:58</td>
<td>27:50</td>
<td>

                    22 of 78

                </td>
<td>M 40-54</td>
<td>

                    6 of 27

                </td>
<td>0:23</td>
<td>28:13</td>
</tr>, <tr data-bib="1297">
<td>30</td>
<td>1297</td>
<td>

                    ADRIANA BRITTON

                </td>
<td>F</td>
<td>53</td>
<td>PORTLAND</td>
<td>OR</td>
<td>9:00</td>
<td>27:54</td>
<td>

                    8 of 113

                </td>
<td>F 40-54</td>
<td>

                    6 of 37

                </td>
<td>0:12</td>
<td>28:06</td>
</tr>, <tr data-bib="1117">
<td>31</td>
<td>1117</td>
<td>

                    MARK WOOD

                </td>
<td>M</td>
<td>43</td>
<td>PORTLAND</td>
<td>OR</td>
<td>9:03</td>
<td>28:05</td>
<td>

                    23 of 78

                </td>
<td>M 40-54</td>
<td>

                    7 of 27

                </td>
<td>0:30</td>
<td>28:35</td>
</tr>, <tr data-bib="1201">
<td>32</td>
<td>1201</td>
<td>

                    STEVE CRANDELL

                </td>
<td>M</td>
<td>61</td>
<td>PORTLAND</td>
<td>OR</td>
<td>9:03</td>
<td>28:06</td>
<td>

                    24 of 78

                </td>
<td>M 55+</td>
<td>

                    2 of 5

                </td>
<td>0:09</td>
<td>28:15</td>
</tr>, <tr data-bib="1110">
<td>33</td>
<td>1110</td>
<td>

                    DARRELL KRIECHBAUM

                </td>
<td>M</td>
<td>53</td>
<td>PORTLAND</td>
<td>OR</td>
<td>9:05</td>
<td>28:11</td>
<td>

                    25 of 78

                </td>
<td>M 40-54</td>
<td>

                    8 of 27

                </td>
<td>0:12</td>
<td>28:23</td>
</tr>, <tr data-bib="1104">
<td>34</td>
<td>1104</td>
<td>

                    JANICE JACOBS

                </td>
<td>F</td>
<td>55</td>
<td>SALEM</td>
<td>OR</td>
<td>9:05</td>
<td>28:11</td>
<td>

                    9 of 113

                </td>
<td>F 55+</td>
<td>

                    1 of 14

                </td>
<td>0:15</td>
<td>28:26</td>
</tr>, <tr data-bib="1300">
<td>35</td>
<td>1300</td>
<td>

                    CORY ANDERSON

                </td>
<td>M</td>
<td>30</td>
<td>PORTLAND</td>
<td>OR</td>
<td>9:06</td>
<td>28:14</td>
<td>

                    26 of 78

                </td>
<td>M 21-39</td>
<td>

                    11 of 33

                </td>
<td>0:19</td>
<td>28:33</td>
</tr>, <tr data-bib="1238">
<td>36</td>
<td>1238</td>
<td>

                    PAUL SUMMERS

                </td>
<td>M</td>
<td>24</td>
<td>PORTLAND</td>
<td>OR</td>
<td>9:08</td>
<td>28:21</td>
<td>

                    27 of 78

                </td>
<td>M 21-39</td>
<td>

                    12 of 33

                </td>
<td>0:15</td>
<td>28:36</td>
</tr>, <tr data-bib="1298">
<td>37</td>
<td>1298</td>
<td>

                    ALEX NGUYEN

                </td>
<td>M</td>
<td>26</td>
<td></td>
<td></td>
<td>9:09</td>
<td>28:22</td>
<td>

                    28 of 78

                </td>
<td>M 21-39</td>
<td>

                    13 of 33

                </td>
<td>0:19</td>
<td>28:41</td>
</tr>, <tr data-bib="1157">
<td>38</td>
<td>1157</td>
<td>

                    JEREMY SWEET

                </td>
<td>M</td>
<td>27</td>
<td>PORTLAND</td>
<td>OR</td>
<td>9:12</td>
<td>28:32</td>
<td>

                    29 of 78

                </td>
<td>M 21-39</td>
<td>

                    14 of 33

                </td>
<td>0:20</td>
<td>28:52</td>
</tr>, <tr data-bib="1106">
<td>39</td>
<td>1106</td>
<td>

                    DANIEL JOHNSTON

                </td>
<td>M</td>
<td>43</td>
<td>PORTLAND</td>
<td>OR</td>
<td>9:12</td>
<td>28:32</td>
<td>

                    30 of 78

                </td>
<td>M 40-54</td>
<td>

                    9 of 27

                </td>
<td>0:12</td>
<td>28:44</td>
</tr>, <tr data-bib="1196">
<td>40</td>
<td>1196</td>
<td>

                    LIZANN DUNEGAN

                </td>
<td>F</td>
<td>53</td>
<td>PORTLAND</td>
<td>OR</td>
<td>9:13</td>
<td>28:34</td>
<td>

                    10 of 113

                </td>
<td>F 40-54</td>
<td>

                    7 of 37

                </td>
<td>0:14</td>
<td>28:48</td>
</tr>, <tr data-bib="1239">
<td>41</td>
<td>1239</td>
<td>

                    ALYX WYNN

                </td>
<td>F</td>
<td>28</td>
<td>PORTLAND</td>
<td>OR</td>
<td>9:14</td>
<td>28:37</td>
<td>

                    11 of 113

                </td>
<td>F 21-39</td>
<td>

                    3 of 53

                </td>
<td>0:21</td>
<td>28:58</td>
</tr>, <tr data-bib="1087">
<td>42</td>
<td>1087</td>
<td>

                    YALOUNDA HUNT

                </td>
<td>F</td>
<td>60</td>
<td>PORTLAND</td>
<td>OR</td>
<td>9:14</td>
<td>28:40</td>
<td>

                    12 of 113

                </td>
<td>F 55+</td>
<td>

                    2 of 14

                </td>
<td>0:09</td>
<td>28:49</td>
</tr>, <tr data-bib="1068">
<td>43</td>
<td>1068</td>
<td>

                    SERGIO RIVERA

                </td>
<td>M</td>
<td>32</td>
<td>PORTLAND</td>
<td>OR</td>
<td>9:15</td>
<td>28:41</td>
<td>

                    31 of 78

                </td>
<td>M 21-39</td>
<td>

                    15 of 33

                </td>
<td>0:21</td>
<td>29:02</td>
</tr>, <tr data-bib="1071">
<td>44</td>
<td>1071</td>
<td>

                    PEDRO FLORES

                </td>
<td>M</td>
<td>42</td>
<td>PORTLAND</td>
<td>OR</td>
<td>9:15</td>
<td>28:42</td>
<td>

                    32 of 78

                </td>
<td>M 40-54</td>
<td>

                    10 of 27

                </td>
<td>0:08</td>
<td>28:50</td>
</tr>, <tr data-bib="1159">
<td>45</td>
<td>1159</td>
<td>

                    JEFF DOWNEY

                </td>
<td>M</td>
<td>36</td>
<td>PORTLAND</td>
<td>OR</td>
<td>9:15</td>
<td>28:42</td>
<td>

                    33 of 78

                </td>
<td>M 21-39</td>
<td>

                    16 of 33

                </td>
<td>0:19</td>
<td>29:01</td>
</tr>, <tr data-bib="1241">
<td>46</td>
<td>1241</td>
<td>

                    NICK SCHUDER

                </td>
<td>M</td>
<td>44</td>
<td>PORTLAND</td>
<td>OR</td>
<td>9:16</td>
<td>28:45</td>
<td>

                    34 of 78

                </td>
<td>M 40-54</td>
<td>

                    11 of 27

                </td>
<td>0:18</td>
<td>29:03</td>
</tr>, <tr data-bib="1023">
<td>47</td>
<td>1023</td>
<td>

                    JOHN GARDNER

                </td>
<td>M</td>
<td>44</td>
<td>PORTLAND</td>
<td>OR</td>
<td>9:18</td>
<td>28:51</td>
<td>

                    35 of 78

                </td>
<td>M 40-54</td>
<td>

                    12 of 27

                </td>
<td>0:25</td>
<td>29:16</td>
</tr>, <tr data-bib="1253">
<td>48</td>
<td>1253</td>
<td>

                    JAZMIN BEMBRY

                </td>
<td>F</td>
<td>23</td>
<td>PORTLAND</td>
<td>OR</td>
<td>9:20</td>
<td>28:56</td>
<td>

                    13 of 113

                </td>
<td>F 21-39</td>
<td>

                    4 of 53

                </td>
<td>0:15</td>
<td>29:11</td>
</tr>, <tr data-bib="1247">
<td>49</td>
<td>1247</td>
<td>

                    THEO KINWAN

                </td>
<td>F</td>
<td></td>
<td></td>
<td></td>
<td>9:24</td>
<td>29:09</td>
<td>

                    14 of 113

                </td>
<td></td>
<td>

                    6 of 9

                </td>
<td>0:10</td>
<td>29:19</td>
</tr>, <tr data-bib="1019">
<td>50</td>
<td>1019</td>
<td>

                    ERIKA TURNEY

                </td>
<td>F</td>
<td>46</td>
<td>BATTLE GROUNDB</td>
<td>WA</td>
<td>9:24</td>
<td>29:10</td>
<td>

                    15 of 113

                </td>
<td>F 40-54</td>
<td>

                    8 of 37

                </td>
<td>0:24</td>
<td>29:34</td>
</tr>, <tr data-bib="1066">
<td>51</td>
<td>1066</td>
<td>

                    MICHELLE FRAZIER

                </td>
<td>F</td>
<td>27</td>
<td>PORTLAND</td>
<td>OR</td>
<td>9:25</td>
<td>29:12</td>
<td>

                    16 of 113

                </td>
<td>F 21-39</td>
<td>

                    5 of 53

                </td>
<td>0:13</td>
<td>29:25</td>
</tr>, <tr data-bib="1151">
<td>52</td>
<td>1151</td>
<td>

                    CHRISTINA LECHER

                </td>
<td>F</td>
<td>31</td>
<td>MILWAUKEE</td>
<td>WI</td>
<td>9:28</td>
<td>29:21</td>
<td>

                    17 of 113

                </td>
<td>F 21-39</td>
<td>

                    6 of 53

                </td>
<td>0:18</td>
<td>29:39</td>
</tr>, <tr data-bib="1152">
<td>53</td>
<td>1152</td>
<td>

                    BERNARD RAHMING

                </td>
<td>M</td>
<td>31</td>
<td>PORTLAND</td>
<td>OR</td>
<td>9:28</td>
<td>29:21</td>
<td>

                    36 of 78

                </td>
<td>M 21-39</td>
<td>

                    17 of 33

                </td>
<td>0:18</td>
<td>29:39</td>
</tr>, <tr data-bib="1095">
<td>54</td>
<td>1095</td>
<td>

                    TROY PICKARD

                </td>
<td>M</td>
<td>36</td>
<td>PORTLAND</td>
<td>OR</td>
<td>9:28</td>
<td>29:22</td>
<td>

                    37 of 78

                </td>
<td>M 21-39</td>
<td>

                    18 of 33

                </td>
<td>0:44</td>
<td>30:06</td>
</tr>, <tr data-bib="1028">
<td>55</td>
<td>1028</td>
<td>

                    JONATHAN TILLMAN

                </td>
<td>M</td>
<td>49</td>
<td>PORTLAND</td>
<td>OR</td>
<td>9:28</td>
<td>29:23</td>
<td>

                    38 of 78


In [8]:
# or

allrows = soup.find_all("tr")
print(allrows[:5])

[<tr colspan="2">
<b>5K:</b>
</tr>, <tr>
<td>Finishers:</td>
<td>191</td>
</tr>, <tr>
<td>Male:</td>
<td>78</td>
</tr>, <tr>
<td>Female:</td>
<td>113</td>
</tr>, <tr class="header">
<th>Place</th>
<th>Bib</th>
<th>Name</th>
<th>Gender</th>
<th>Age</th>
<th>City</th>
<th>State</th>
<th>Chip Pace</th>
<th>Time</th>
<th>Gender Place</th>
<th>Age Group</th>
<th>Age Group Place</th>
<th>Time to Start</th>
<th>Gun Time</th>
</tr>]

In [9]:
# or 
allrows = soup.find_all("tr")
print(allrows[0])

<tr colspan="2">
<b>5K:</b>
</tr>

In [10]:
# or 
allrows = soup.find_all("tr")
print(allrows[:10])

[<tr colspan="2">
<b>5K:</b>
</tr>, <tr>
<td>Finishers:</td>
<td>191</td>
</tr>, <tr>
<td>Male:</td>
<td>78</td>
</tr>, <tr>
<td>Female:</td>
<td>113</td>
</tr>, <tr class="header">
<th>Place</th>
<th>Bib</th>
<th>Name</th>
<th>Gender</th>
<th>Age</th>
<th>City</th>
<th>State</th>
<th>Chip Pace</th>
<th>Time</th>
<th>Gender Place</th>
<th>Age Group</th>
<th>Age Group Place</th>
<th>Time to Start</th>
<th>Gun Time</th>
</tr>, <tr data-bib="1191">
<td>1</td>
<td>1191</td>
<td>

                    MAX RANDOLPH

                </td>
<td>M</td>
<td>29</td>
<td>WASHINGTON</td>
<td>DC</td>
<td>5:25</td>
<td>16:48</td>
<td>

                    1 of 78

                </td>
<td>M 21-39</td>
<td>

                    1 of 33

                </td>
<td>0:08</td>
<td>16:56</td>
</tr>, <tr data-bib="1080">
<td>2</td>
<td>1080</td>
<td>

                    NEED NAME KAISER RUNNER

                </td>
<td>M</td>
<td>25</td>
<td>PORTLAND</td>
<td>OR</td>
<td>5:39</td>
<td>17:31</td>
<td>

                    2 of 78

                </td>
<td>M 21-39</td>
<td>

                    2 of 33

                </td>
<td>0:09</td>
<td>17:40</td>
</tr>, <tr data-bib="1275">
<td>3</td>
<td>1275</td>
<td>

                    DAN FRANEK

                </td>
<td>M</td>
<td>52</td>
<td>PORTLAND</td>
<td>OR</td>
<td>5:53</td>
<td>18:15</td>
<td>

                    3 of 78

                </td>
<td>M 40-54</td>
<td>

                    1 of 27

                </td>
<td>0:07</td>
<td>18:22</td>
</tr>, <tr data-bib="1223">
<td>4</td>
<td>1223</td>
<td>

                    PAUL TAYLOR

                </td>
<td>M</td>
<td>54</td>
<td>PORTLAND</td>
<td>OR</td>
<td>5:58</td>
<td>18:31</td>
<td>

                    4 of 78

                </td>
<td>M 40-54</td>
<td>

                    2 of 27

                </td>
<td>0:07</td>
<td>18:38</td>
</tr>, <tr data-bib="1245">
<td>5</td>
<td>1245</td>
<td>

                    THEO KINMAN

                </td>
<td>M</td>
<td>22</td>
<td></td>
<td></td>
<td>6:17</td>
<td>19:31</td>
<td>

                    5 of 78

                </td>
<td>M 21-39</td>
<td>

                    3 of 33

                </td>
<td>0:09</td>
<td>19:40</td>
</tr>]

In [11]:
allrows = soup.find_all("tr")
for row in allrows:
    row_list = row.find_all("td")
print(row_list)

[<td>191</td>, <td>1216</td>, <td>

                    ZULMA OCHOA

                </td>, <td>F</td>, <td>40</td>, <td>GRESHAM</td>, <td>OR</td>, <td>33:22</td>, <td>1:43:27</td>, <td>

                    113 of 113

                </td>, <td>F 40-54</td>, <td>

                    37 of 37

                </td>, <td>0:00</td>, <td>1:43:27</td>]

In [12]:
allrows = soup.find_all("tr")
for row in allrows:
    row_list = row.find_all("td")
print(row_list)
for cell in row_list:
    print(cell.text)

[<td>191</td>, <td>1216</td>, <td>

                    ZULMA OCHOA

                </td>, <td>F</td>, <td>40</td>, <td>GRESHAM</td>, <td>OR</td>, <td>33:22</td>, <td>1:43:27</td>, <td>

                    113 of 113

                </td>, <td>F 40-54</td>, <td>

                    37 of 37

                </td>, <td>0:00</td>, <td>1:43:27</td>]
191
1216


                    ZULMA OCHOA


F
40
GRESHAM
OR
33:22
1:43:27


                    113 of 113


F 40-54


                    37 of 37


0:00
1:43:27

In [13]:
data = []
allrows = soup.find_all("tr")
for row in allrows:
    row_list = row.find_all("td")
    dataRow = []
    for cell in row_list:
        dataRow.append(cell.text)
    data.append(dataRow)
print(data[2:])

[['Male:', '78'], ['Female:', '113'], [], ['1', '1191', '\r\n\r\n                    MAX RANDOLPH\r\n\r\n                ', 'M', '29', 'WASHINGTON', 'DC', '5:25', '16:48', '\r\n\r\n                    1 of 78\r\n\r\n                ', 'M 21-39', '\r\n\r\n                    1 of 33\r\n\r\n                ', '0:08', '16:56'], ['2', '1080', '\r\n\r\n                    NEED NAME KAISER RUNNER\r\n\r\n                ', 'M', '25', 'PORTLAND', 'OR', '5:39', '17:31', '\r\n\r\n                    2 of 78\r\n\r\n                ', 'M 21-39', '\r\n\r\n                    2 of 33\r\n\r\n                ', '0:09', '17:40'], ['3', '1275', '\r\n\r\n                    DAN FRANEK\r\n\r\n                ', 'M', '52', 'PORTLAND', 'OR', '5:53', '18:15', '\r\n\r\n                    3 of 78\r\n\r\n                ', 'M 40-54', '\r\n\r\n                    1 of 27\r\n\r\n                ', '0:07', '18:22'], ['4', '1223', '\r\n\r\n                    PAUL TAYLOR\r\n\r\n                ', 'M', '54', 'PORTLAND', 'OR', '5:58', '18:31', '\r\n\r\n                    4 of 78\r\n\r\n                ', 'M 40-54', '\r\n\r\n                    2 of 27\r\n\r\n                ', '0:07', '18:38'], ['5', '1245', '\r\n\r\n                    THEO KINMAN\r\n\r\n                ', 'M', '22', '', '', '6:17', '19:31', '\r\n\r\n                    5 of 78\r\n\r\n                ', 'M 21-39', '\r\n\r\n                    3 of 33\r\n\r\n                ', '0:09', '19:40'], ['6', '1185', '\r\n\r\n                    MELISSA GIRGIS\r\n\r\n                ', 'F', '27', 'PORTLAND', 'OR', '6:20', '19:39', '\r\n\r\n                    1 of 113\r\n\r\n                ', 'F 21-39', '\r\n\r\n                    1 of 53\r\n\r\n                ', '0:07', '19:46'], ['7', '1251', '\r\n\r\n                    CHARLIE COGGESHALL\r\n\r\n                ', 'M', '39', 'PORTLAND', 'OR', '6:24', '19:51', '\r\n\r\n                    6 of 78\r\n\r\n                ', 'M 21-39', '\r\n\r\n                    4 of 33\r\n\r\n                ', '0:10', '20:01'], ['8', '1154', '\r\n\r\n                    UNKNOWN RUNNER SEE TIMER\r\n\r\n                ', 'M', '', '', '', '8:03', '24:58', '\r\n\r\n                    7 of 78\r\n\r\n                ', '', '\r\n\r\n                    1 of 9\r\n\r\n                ', '2:00', '26:58'], ['9', '1163', '\r\n\r\n                    UNKNOWN RUNNER SEE TIMER\r\n\r\n                ', 'M', '', '', '', '8:04', '25:01', '\r\n\r\n                    8 of 78\r\n\r\n                ', '', '\r\n\r\n                    2 of 9\r\n\r\n                ', '1:59', '27:00'], ['10', '1242', '\r\n\r\n                    KIMONTI WILSON\r\n\r\n                ', 'F', '48', '', '', '8:04', '25:01', '\r\n\r\n                    2 of 113\r\n\r\n                ', 'F 40-54', '\r\n\r\n                    1 of 37\r\n\r\n                ', '1:59', '27:00'], ['11', '1017', '\r\n\r\n                    COREY MCMANUS\r\n\r\n                ', 'M', '37', 'BEAVERTON', 'OR', '8:09', '25:17', '\r\n\r\n                    9 of 78\r\n\r\n                ', 'M 21-39', '\r\n\r\n                    5 of 33\r\n\r\n                ', '0:22', '25:39'], ['12', '1112', '\r\n\r\n                    MITCHELL JOHNSON\r\n\r\n                ', 'M', '25', 'PORTLAND', 'OR', '8:13', '25:31', '\r\n\r\n                    10 of 78\r\n\r\n                ', 'M 21-39', '\r\n\r\n                    6 of 33\r\n\r\n                ', '0:15', '25:46'], ['13', '1062', '\r\n\r\n                    ALEX KABA\r\n\r\n                ', 'M', '36', 'PORTLAND', 'OR', '8:14', '25:31', '\r\n\r\n                    11 of 78\r\n\r\n                ', 'M 21-39', '\r\n\r\n                    7 of 33\r\n\r\n                ', '0:14', '25:45'], ['14', '1227', '\r\n\r\n                    ROBYN MCGILLIS\r\n\r\n                ', 'F', '44', 'PORTLAND', 'OR', '8:18', '25:44', '\r\n\r\n                    3 of 113\r\n\r\n                ', 'F 40-54', '\r\n\r\n                    2 of 37\r\n\r\n                ', '0:08', '25:52'], ['15', '1067', '\r\n\r\n                    MITCHELL WARDEN\r\n\r\n                ', 'M', '29', 'PORTLAND', 'OR', '8:19', '25:46', '\r\n\r\n                    12 of 78\r\n\r\n                ', 'M 21-39', '\r\n\r\n                    8 of 33\r\n\r\n                ', '0:14', '26:00'], ['16', '1136', '\r\n\r\n                    JULIA METZ\r\n\r\n                ', 'F', '32', 'PORTLAND', 'OR', '8:33', '26:31', '\r\n\r\n                    4 of 113\r\n\r\n                ', 'F 21-39', '\r\n\r\n                    2 of 53\r\n\r\n                ', '0:33', '27:04'], ['17', '1199', '\r\n\r\n                    JEREMY AREZZINI\r\n\r\n                ', 'M', '38', 'LAKE OSWEGO', 'OR', '8:37', '26:44', '\r\n\r\n                    13 of 78\r\n\r\n                ', 'M 21-39', '\r\n\r\n                    9 of 33\r\n\r\n                ', '0:41', '27:25'], ['18', '1252', '\r\n\r\n                    ETHAN POWELL\r\n\r\n                ', 'M', '', '', '', '8:40', '26:52', '\r\n\r\n                    14 of 78\r\n\r\n                ', '', '\r\n\r\n                    3 of 9\r\n\r\n                ', '0:11', '27:03'], ['19', '1231', '\r\n\r\n                    TIMOTHY KEARNEY\r\n\r\n                ', 'M', '42', 'PORTLAND', 'OR', '8:42', '26:58', '\r\n\r\n                    15 of 78\r\n\r\n                ', 'M 40-54', '\r\n\r\n                    3 of 27\r\n\r\n                ', '0:11', '27:09'], ['20', '1108', '\r\n\r\n                    TIMOTHY RINGERING\r\n\r\n                ', 'M', '50', 'VANCOUVER', 'WA', '8:43', '27:02', '\r\n\r\n                    16 of 78\r\n\r\n                ', 'M 40-54', '\r\n\r\n                    4 of 27\r\n\r\n                ', '0:10', '27:12'], ['21', '1118', '\r\n\r\n                    PONTUS JADERHOLM\r\n\r\n                ', 'M', '43', 'PORTLAND', 'OR', '8:45', '27:08', '\r\n\r\n                    17 of 78\r\n\r\n                ', 'M 40-54', '\r\n\r\n                    5 of 27\r\n\r\n                ', '0:13', '27:21'], ['22', '1246', '\r\n\r\n                    KERRY FLAGG\r\n\r\n                ', 'M', '', '', '', '8:45', '27:10', '\r\n\r\n                    18 of 78\r\n\r\n                ', '', '\r\n\r\n                    4 of 9\r\n\r\n                ', '0:10', '27:20'], ['23', '1244', '\r\n\r\n                    JARRED FLAGG\r\n\r\n                ', 'M', '', '', '', '8:46', '27:11', '\r\n\r\n                    19 of 78\r\n\r\n                ', '', '\r\n\r\n                    5 of 9\r\n\r\n                ', '0:10', '27:21'], ['24', '1224', '\r\n\r\n                    KEN SKEEN\r\n\r\n                ', 'M', '57', 'PORTLAND', 'OR', '8:46', '27:12', '\r\n\r\n                    20 of 78\r\n\r\n                ', 'M 55+', '\r\n\r\n                    1 of 5\r\n\r\n                ', '0:18', '27:30'], ['25', '1065', '\r\n\r\n                    SARA KOPTON\r\n\r\n                ', 'F', '40', 'PORTLAND', 'OR', '8:51', '27:27', '\r\n\r\n                    5 of 113\r\n\r\n                ', 'F 40-54', '\r\n\r\n                    3 of 37\r\n\r\n                ', '0:20', '27:47'], ['26', '1274', '\r\n\r\n                    KAISER GUEST\r\n\r\n                ', 'F', '40', 'PORTLAND', 'OR', '8:54', '27:37', '\r\n\r\n                    6 of 113\r\n\r\n                ', 'F 40-54', '\r\n\r\n                    4 of 37\r\n\r\n                ', '0:09', '27:46'], ['27', '1208', '\r\n\r\n                    JUSTIN PERZ\r\n\r\n                ', 'M', '33', 'PORTLAND', 'OR', '8:55', '27:39', '\r\n\r\n                    21 of 78\r\n\r\n                ', 'M 21-39', '\r\n\r\n                    10 of 33\r\n\r\n                ', '0:38', '28:17'], ['28', '1072', '\r\n\r\n                    ESTELA SÁNCHEZ\r\n\r\n                ', 'F', '41', 'PORTLAND', 'OR', '8:57', '27:45', '\r\n\r\n                    7 of 113\r\n\r\n                ', 'F 40-54', '\r\n\r\n                    5 of 37\r\n\r\n                ', '0:08', '27:53'], ['29', '1018', '\r\n\r\n                    JASON WILLIAMS\r\n\r\n                ', 'M', '41', 'PORTLAND', 'OR', '8:58', '27:50', '\r\n\r\n                    22 of 78\r\n\r\n                ', 'M 40-54', '\r\n\r\n                    6 of 27\r\n\r\n                ', '0:23', '28:13'], ['30', '1297', '\r\n\r\n                    ADRIANA BRITTON\r\n\r\n                ', 'F', '53', 'PORTLAND', 'OR', '9:00', '27:54', '\r\n\r\n                    8 of 113\r\n\r\n                ', 'F 40-54', '\r\n\r\n                    6 of 37\r\n\r\n                ', '0:12', '28:06'], ['31', '1117', '\r\n\r\n                    MARK WOOD\r\n\r\n                ', 'M', '43', 'PORTLAND', 'OR', '9:03', '28:05', '\r\n\r\n                    23 of 78\r\n\r\n                ', 'M 40-54', '\r\n\r\n                    7 of 27\r\n\r\n                ', '0:30', '28:35'], ['32', '1201', '\r\n\r\n                    STEVE CRANDELL\r\n\r\n                ', 'M', '61', 'PORTLAND', 'OR', '9:03', '28:06', '\r\n\r\n                    24 of 78\r\n\r\n                ', 'M 55+', '\r\n\r\n                    2 of 5\r\n\r\n                ', '0:09', '28:15'], ['33', '1110', '\r\n\r\n                    DARRELL KRIECHBAUM\r\n\r\n                ', 'M', '53', 'PORTLAND', 'OR', '9:05', '28:11', '\r\n\r\n                    25 of 78\r\n\r\n                ', 'M 40-54', '\r\n\r\n                    8 of 27\r\n\r\n                ', '0:12', '28:23'], ['34', '1104', '\r\n\r\n                    JANICE JACOBS\r\n\r\n                ', 'F', '55', 'SALEM', 'OR', '9:05', '28:11', '\r\n\r\n                    9 of 113\r\n\r\n                ', 'F 55+', '\r\n\r\n                    1 of 14\r\n\r\n                ', '0:15', '28:26'], ['35', '1300', '\r\n\r\n                    CORY ANDERSON\r\n\r\n                ', 'M', '30', 'PORTLAND', 'OR', '9:06', '28:14', '\r\n\r\n                    26 of 78\r\n\r\n                ', 'M 21-39', '\r\n\r\n                    11 of 33\r\n\r\n                ', '0:19', '28:33'], ['36', '1238', '\r\n\r\n                    PAUL SUMMERS\r\n\r\n                ', 'M', '24', 'PORTLAND', 'OR', '9:08', '28:21', '\r\n\r\n                    27 of 78\r\n\r\n                ', 'M 21-39', '\r\n\r\n                    12 of 33\r\n\r\n                ', '0:15', '28:36'], ['37', '1298', '\r\n\r\n                    ALEX NGUYEN\r\n\r\n                ', 'M', '26', '', '', '9:09', '28:22', '\r\n\r\n                    28 of 78\r\n\r\n                ', 'M 21-39', '\r\n\r\n                    13 of 33\r\n\r\n                ', '0:19', '28:41'], ['38', '1157', '\r\n\r\n                    JEREMY SWEET\r\n\r\n                ', 'M', '27', 'PORTLAND', 'OR', '9:12', '28:32', '\r\n\r\n                    29 of 78\r\n\r\n                ', 'M 21-39', '\r\n\r\n                    14 of 33\r\n\r\n                ', '0:20', '28:52'], ['39', '1106', '\r\n\r\n                    DANIEL JOHNSTON\r\n\r\n                ', 'M', '43', 'PORTLAND', 'OR', '9:12', '28:32', '\r\n\r\n                    30 of 78\r\n\r\n                ', 'M 40-54', '\r\n\r\n                    9 of 27\r\n\r\n                ', '0:12', '28:44'], ['40', '1196', '\r\n\r\n                    LIZANN DUNEGAN\r\n\r\n                ', 'F', '53', 'PORTLAND', 'OR', '9:13', '28:34', '\r\n\r\n                    10 of 113\r\n\r\n                ', 'F 40-54', '\r\n\r\n                    7 of 37\r\n\r\n                ', '0:14', '28:48'], ['41', '1239', '\r\n\r\n                    ALYX WYNN\r\n\r\n                ', 'F', '28', 'PORTLAND', 'OR', '9:14', '28:37', '\r\n\r\n                    11 of 113\r\n\r\n                ', 'F 21-39', '\r\n\r\n                    3 of 53\r\n\r\n                ', '0:21', '28:58'], ['42', '1087', '\r\n\r\n                    YALOUNDA HUNT\r\n\r\n                ', 'F', '60', 'PORTLAND', 'OR', '9:14', '28:40', '\r\n\r\n                    12 of 113\r\n\r\n                ', 'F 55+', '\r\n\r\n                    2 of 14\r\n\r\n                ', '0:09', '28:49'], ['43', '1068', '\r\n\r\n                    SERGIO RIVERA\r\n\r\n                ', 'M', '32', 'PORTLAND', 'OR', '9:15', '28:41', '\r\n\r\n                    31 of 78\r\n\r\n                ', 'M 21-39', '\r\n\r\n                    15 of 33\r\n\r\n                ', '0:21', '29:02'], ['44', '1071', '\r\n\r\n                    PEDRO FLORES\r\n\r\n                ', 'M', '42', 'PORTLAND', 'OR', '9:15', '28:42', '\r\n\r\n                    32 of 78\r\n\r\n                ', 'M 40-54', '\r\n\r\n                    10 of 27\r\n\r\n                ', '0:08', '28:50'], ['45', '1159', '\r\n\r\n                    JEFF DOWNEY\r\n\r\n                ', 'M', '36', 'PORTLAND', 'OR', '9:15', '28:42', '\r\n\r\n                    33 of 78\r\n\r\n                ', 'M 21-39', '\r\n\r\n                    16 of 33\r\n\r\n                ', '0:19', '29:01'], ['46', '1241', '\r\n\r\n                    NICK SCHUDER\r\n\r\n                ', 'M', '44', 'PORTLAND', 'OR', '9:16', '28:45', '\r\n\r\n                    34 of 78\r\n\r\n                ', 'M 40-54', '\r\n\r\n                    11 of 27\r\n\r\n                ', '0:18', '29:03'], ['47', '1023', '\r\n\r\n                    JOHN GARDNER\r\n\r\n                ', 'M', '44', 'PORTLAND', 'OR', '9:18', '28:51', '\r\n\r\n                    35 of 78\r\n\r\n                ', 'M 40-54', '\r\n\r\n                    12 of 27\r\n\r\n                ', '0:25', '29:16'], ['48', '1253', '\r\n\r\n                    JAZMIN BEMBRY\r\n\r\n                ', 'F', '23', 'PORTLAND', 'OR', '9:20', '28:56', '\r\n\r\n                    13 of 113\r\n\r\n                ', 'F 21-39', '\r\n\r\n                    4 of 53\r\n\r\n                ', '0:15', '29:11'], ['49', '1247', '\r\n\r\n                    THEO KINWAN\r\n\r\n                ', 'F', '', '', '', '9:24', '29:09', '\r\n\r\n                    14 of 113\r\n\r\n                ', '', '\r\n\r\n                    6 of 9\r\n\r\n                ', '0:10', '29:19'], ['50', '1019', '\r\n\r\n                    ERIKA TURNEY\r\n\r\n                ', 'F', '46', 'BATTLE GROUNDB', 'WA', '9:24', '29:10', '\r\n\r\n                    15 of 113\r\n\r\n                ', 'F 40-54', '\r\n\r\n                    8 of 37\r\n\r\n                ', '0:24', '29:34'], ['51', '1066', '\r\n\r\n                    MICHELLE FRAZIER\r\n\r\n                ', 'F', '27', 'PORTLAND', 'OR', '9:25', '29:12', '\r\n\r\n                    16 of 113\r\n\r\n                ', 'F 21-39', '\r\n\r\n                    5 of 53\r\n\r\n                ', '0:13', '29:25'], ['52', '1151', '\r\n\r\n                    CHRISTINA LECHER\r\n\r\n                ', 'F', '31', 'MILWAUKEE', 'WI', '9:28', '29:21', '\r\n\r\n                    17 of 113\r\n\r\n                ', 'F 21-39', '\r\n\r\n                    6 of 53\r\n\r\n                ', '0:18', '29:39'], ['53', '1152', '\r\n\r\n                    BERNARD RAHMING\r\n\r\n                ', 'M', '31', 'PORTLAND', 'OR', '9:28', '29:21', '\r\n\r\n                    36 of 78\r\n\r\n                ', 'M 21-39', '\r\n\r\n                    17 of 33\r\n\r\n                ', '0:18', '29:39'], ['54', '1095', '\r\n\r\n                    TROY PICKARD\r\n\r\n                ', 'M', '36', 'PORTLAND', 'OR', '9:28', '29:22', '\r\n\r\n                    37 of 78\r\n\r\n                ', 'M 21-39', '\r\n\r\n                    18 of 33\r\n\r\n                ', '0:44', '30:06'], ['55', '1028', '\r\n\r\n                    JONATHAN TILLMAN\r\n\r\n                ', 'M', '49', 'PORTLAND', 'OR', '9:28', '29:23', '\r\n\r\n                    38 of 78\r\n\r\n                ', 'M 40-54', '\r\n\r\n                    13 of 27\r\n\r\n                ', '0:24', '29:47'], ['56', '1174', '\r\n\r\n                    CYNJAYSHA BOLES\r\n\r\n                ', 'F', '26', 'PORTLAND', 'OR', '9:36', '29:46', '\r\n\r\n                    18 of 113\r\n\r\n                ', 'F 21-39', '\r\n\r\n                    7 of 53\r\n\r\n                ', '0:09', '29:55'], ['57', '1013', '\r\n\r\n                    TERESA MCGRATH\r\n\r\n                ', 'F', '65', 'PORTLAND', 'OR', '9:37', '29:51', '\r\n\r\n                    19 of 113\r\n\r\n                ', 'F 55+', '\r\n\r\n                    3 of 14\r\n\r\n                ', '0:10', '30:01'], ['58', '1237', '\r\n\r\n                    ERYN HOERSTER\r\n\r\n                ', 'F', '37', 'PORTLAND', 'OR', '9:53', '30:41', '\r\n\r\n                    20 of 113\r\n\r\n                ', 'F 21-39', '\r\n\r\n                    8 of 53\r\n\r\n                ', '0:40', '31:21'], ['59', '1230', '\r\n\r\n                    EDUARDO ARIZAGA\r\n\r\n                ', 'M', '38', 'PORTLAND', 'OR', '9:58', '30:55', '\r\n\r\n                    39 of 78\r\n\r\n                ', 'M 21-39', '\r\n\r\n                    19 of 33\r\n\r\n                ', '0:47', '31:42'], ['60', '1236', '\r\n\r\n                    BEN HOERSTER\r\n\r\n                ', 'M', '37', 'PORTLAND', 'OR', '10:09', '31:29', '\r\n\r\n                    40 of 78\r\n\r\n                ', 'M 21-39', '\r\n\r\n                    20 of 33\r\n\r\n                ', '0:43', '32:12'], ['61', '1125', '\r\n\r\n                    ABIGAIL VAN GELDER\r\n\r\n                ', 'F', '36', 'PORTLAND', 'OR', '10:12', '31:37', '\r\n\r\n                    21 of 113\r\n\r\n                ', 'F 21-39', '\r\n\r\n                    9 of 53\r\n\r\n                ', '0:16', '31:53'], ['62', '1053', '\r\n\r\n                    DAMIANA KING\r\n\r\n                ', 'F', '38', 'PORTLAND', 'OR', '10:20', '32:02', '\r\n\r\n                    22 of 113\r\n\r\n                ', 'F 21-39', '\r\n\r\n                    10 of 53\r\n\r\n                ', '0:12', '32:14'], ['63', '1010', '\r\n\r\n                    HEATHER CERMAK\r\n\r\n                ', 'F', '29', 'PORTLAND', 'OR', '10:23', '32:11', '\r\n\r\n                    23 of 113\r\n\r\n                ', 'F 21-39', '\r\n\r\n                    11 of 53\r\n\r\n                ', '0:41', '32:52'], ['64', '1011', '\r\n\r\n                    COLE CHRIST\r\n\r\n                ', 'M', '19', 'PORTLAND', 'OR', '10:23', '32:11', '\r\n\r\n                    41 of 78\r\n\r\n                ', 'M 20 and Under', '\r\n\r\n                    1 of 7\r\n\r\n                ', '0:42', '32:53'], ['65', '1179', '\r\n\r\n                    MIRIAN HINOJOSA\r\n\r\n                ', 'F', '40', 'MILWAUKIE', 'OR', '10:34', '32:48', '\r\n\r\n                    24 of 113\r\n\r\n                ', 'F 40-54', '\r\n\r\n                    9 of 37\r\n\r\n                ', '0:14', '33:02'], ['66', '1183', '\r\n\r\n                    CAMERON SEIDLING\r\n\r\n                ', 'M', '28', 'PORTLAND', 'OR', '10:44', '33:16', '\r\n\r\n                    42 of 78\r\n\r\n                ', 'M 21-39', '\r\n\r\n                    21 of 33\r\n\r\n                ', '0:37', '33:53'], ['67', '1137', '\r\n\r\n                    LARRY JENKINS\r\n\r\n                ', 'M', '31', 'PORTLAND', 'OR', '10:44', '33:16', '\r\n\r\n                    43 of 78\r\n\r\n                ', 'M 21-39', '\r\n\r\n                    22 of 33\r\n\r\n                ', '0:34', '33:50'], ['68', '1173', '\r\n\r\n                    ALYS MEYER\r\n\r\n                ', 'F', '12', 'PORTLAND', 'OR', '10:49', '33:33', '\r\n\r\n                    25 of 113\r\n\r\n                ', 'F 20 and Under', '\r\n\r\n                    1 of 6\r\n\r\n                ', '0:27', '34:00'], ['69', '1103', '\r\n\r\n                    SARAH MEYER\r\n\r\n                ', 'F', '34', 'PORTLAND', 'OR', '10:50', '33:36', '\r\n\r\n                    26 of 113\r\n\r\n                ', 'F 21-39', '\r\n\r\n                    12 of 53\r\n\r\n                ', '0:26', '34:02'], ['70', '1100', '\r\n\r\n                    ELIZABETH TAYLOR\r\n\r\n                ', 'F', '39', 'PORTLAND', 'OR', '10:51', '33:40', '\r\n\r\n                    27 of 113\r\n\r\n                ', 'F 21-39', '\r\n\r\n                    13 of 53\r\n\r\n                ', '0:37', '34:17'], ['7

In [14]:
data = []
allrows = soup.find_all("tr")
for row in allrows:
    row_list = row.find_all("td")
    dataRow = []
    for cell in row_list:
        dataRow.append(cell.text)
    data.append(dataRow)
titles = data[0]
data = data[1:]
print(titles)
print(data[-2:])

[]
[['190', '2087', '\r\n\r\n                    LEESHA POSEY\r\n\r\n                ', 'F', '43', 'PORTLAND', 'OR', '30:17', '1:33:53', '\r\n\r\n                    112 of 113\r\n\r\n                ', 'F 40-54', '\r\n\r\n                    36 of 37\r\n\r\n                ', '0:00', '1:33:53'], ['191', '1216', '\r\n\r\n                    ZULMA OCHOA\r\n\r\n                ', 'F', '40', 'GRESHAM', 'OR', '33:22', '1:43:27', '\r\n\r\n                    113 of 113\r\n\r\n                ', 'F 40-54', '\r\n\r\n                    37 of 37\r\n\r\n                ', '0:00', '1:43:27']]

In [15]:
data = []
allrows = soup.find_all("tr")
for row in allrows:
    row_list = row.find_all("td")
    dataRow = []
    for cell in row_list:
        dataRow.append(cell.text)
    data.append(dataRow)
data = data[1:]
print(data[-2:])

[['190', '2087', '\r\n\r\n                    LEESHA POSEY\r\n\r\n                ', 'F', '43', 'PORTLAND', 'OR', '30:17', '1:33:53', '\r\n\r\n                    112 of 113\r\n\r\n                ', 'F 40-54', '\r\n\r\n                    36 of 37\r\n\r\n                ', '0:00', '1:33:53'], ['191', '1216', '\r\n\r\n                    ZULMA OCHOA\r\n\r\n                ', 'F', '40', 'GRESHAM', 'OR', '33:22', '1:43:27', '\r\n\r\n                    113 of 113\r\n\r\n                ', 'F 40-54', '\r\n\r\n                    37 of 37\r\n\r\n                ', '0:00', '1:43:27']]

In [16]:
# Dataframes

df = pd.DataFrame(data)
print(data)

[['Finishers:', '191'], ['Male:', '78'], ['Female:', '113'], [], ['1', '1191', '\r\n\r\n                    MAX RANDOLPH\r\n\r\n                ', 'M', '29', 'WASHINGTON', 'DC', '5:25', '16:48', '\r\n\r\n                    1 of 78\r\n\r\n                ', 'M 21-39', '\r\n\r\n                    1 of 33\r\n\r\n                ', '0:08', '16:56'], ['2', '1080', '\r\n\r\n                    NEED NAME KAISER RUNNER\r\n\r\n                ', 'M', '25', 'PORTLAND', 'OR', '5:39', '17:31', '\r\n\r\n                    2 of 78\r\n\r\n                ', 'M 21-39', '\r\n\r\n                    2 of 33\r\n\r\n                ', '0:09', '17:40'], ['3', '1275', '\r\n\r\n                    DAN FRANEK\r\n\r\n                ', 'M', '52', 'PORTLAND', 'OR', '5:53', '18:15', '\r\n\r\n                    3 of 78\r\n\r\n                ', 'M 40-54', '\r\n\r\n                    1 of 27\r\n\r\n                ', '0:07', '18:22'], ['4', '1223', '\r\n\r\n                    PAUL TAYLOR\r\n\r\n                ', 'M', '54', 'PORTLAND', 'OR', '5:58', '18:31', '\r\n\r\n                    4 of 78\r\n\r\n                ', 'M 40-54', '\r\n\r\n                    2 of 27\r\n\r\n                ', '0:07', '18:38'], ['5', '1245', '\r\n\r\n                    THEO KINMAN\r\n\r\n                ', 'M', '22', '', '', '6:17', '19:31', '\r\n\r\n                    5 of 78\r\n\r\n                ', 'M 21-39', '\r\n\r\n                    3 of 33\r\n\r\n                ', '0:09', '19:40'], ['6', '1185', '\r\n\r\n                    MELISSA GIRGIS\r\n\r\n                ', 'F', '27', 'PORTLAND', 'OR', '6:20', '19:39', '\r\n\r\n                    1 of 113\r\n\r\n                ', 'F 21-39', '\r\n\r\n                    1 of 53\r\n\r\n                ', '0:07', '19:46'], ['7', '1251', '\r\n\r\n                    CHARLIE COGGESHALL\r\n\r\n                ', 'M', '39', 'PORTLAND', 'OR', '6:24', '19:51', '\r\n\r\n                    6 of 78\r\n\r\n                ', 'M 21-39', '\r\n\r\n                    4 of 33\r\n\r\n                ', '0:10', '20:01'], ['8', '1154', '\r\n\r\n                    UNKNOWN RUNNER SEE TIMER\r\n\r\n                ', 'M', '', '', '', '8:03', '24:58', '\r\n\r\n                    7 of 78\r\n\r\n                ', '', '\r\n\r\n                    1 of 9\r\n\r\n                ', '2:00', '26:58'], ['9', '1163', '\r\n\r\n                    UNKNOWN RUNNER SEE TIMER\r\n\r\n                ', 'M', '', '', '', '8:04', '25:01', '\r\n\r\n                    8 of 78\r\n\r\n                ', '', '\r\n\r\n                    2 of 9\r\n\r\n                ', '1:59', '27:00'], ['10', '1242', '\r\n\r\n                    KIMONTI WILSON\r\n\r\n                ', 'F', '48', '', '', '8:04', '25:01', '\r\n\r\n                    2 of 113\r\n\r\n                ', 'F 40-54', '\r\n\r\n                    1 of 37\r\n\r\n                ', '1:59', '27:00'], ['11', '1017', '\r\n\r\n                    COREY MCMANUS\r\n\r\n                ', 'M', '37', 'BEAVERTON', 'OR', '8:09', '25:17', '\r\n\r\n                    9 of 78\r\n\r\n                ', 'M 21-39', '\r\n\r\n                    5 of 33\r\n\r\n                ', '0:22', '25:39'], ['12', '1112', '\r\n\r\n                    MITCHELL JOHNSON\r\n\r\n                ', 'M', '25', 'PORTLAND', 'OR', '8:13', '25:31', '\r\n\r\n                    10 of 78\r\n\r\n                ', 'M 21-39', '\r\n\r\n                    6 of 33\r\n\r\n                ', '0:15', '25:46'], ['13', '1062', '\r\n\r\n                    ALEX KABA\r\n\r\n                ', 'M', '36', 'PORTLAND', 'OR', '8:14', '25:31', '\r\n\r\n                    11 of 78\r\n\r\n                ', 'M 21-39', '\r\n\r\n                    7 of 33\r\n\r\n                ', '0:14', '25:45'], ['14', '1227', '\r\n\r\n                    ROBYN MCGILLIS\r\n\r\n                ', 'F', '44', 'PORTLAND', 'OR', '8:18', '25:44', '\r\n\r\n                    3 of 113\r\n\r\n                ', 'F 40-54', '\r\n\r\n                    2 of 37\r\n\r\n                ', '0:08', '25:52'], ['15', '1067', '\r\n\r\n                    MITCHELL WARDEN\r\n\r\n                ', 'M', '29', 'PORTLAND', 'OR', '8:19', '25:46', '\r\n\r\n                    12 of 78\r\n\r\n                ', 'M 21-39', '\r\n\r\n                    8 of 33\r\n\r\n                ', '0:14', '26:00'], ['16', '1136', '\r\n\r\n                    JULIA METZ\r\n\r\n                ', 'F', '32', 'PORTLAND', 'OR', '8:33', '26:31', '\r\n\r\n                    4 of 113\r\n\r\n                ', 'F 21-39', '\r\n\r\n                    2 of 53\r\n\r\n                ', '0:33', '27:04'], ['17', '1199', '\r\n\r\n                    JEREMY AREZZINI\r\n\r\n                ', 'M', '38', 'LAKE OSWEGO', 'OR', '8:37', '26:44', '\r\n\r\n                    13 of 78\r\n\r\n                ', 'M 21-39', '\r\n\r\n                    9 of 33\r\n\r\n                ', '0:41', '27:25'], ['18', '1252', '\r\n\r\n                    ETHAN POWELL\r\n\r\n                ', 'M', '', '', '', '8:40', '26:52', '\r\n\r\n                    14 of 78\r\n\r\n                ', '', '\r\n\r\n                    3 of 9\r\n\r\n                ', '0:11', '27:03'], ['19', '1231', '\r\n\r\n                    TIMOTHY KEARNEY\r\n\r\n                ', 'M', '42', 'PORTLAND', 'OR', '8:42', '26:58', '\r\n\r\n                    15 of 78\r\n\r\n                ', 'M 40-54', '\r\n\r\n                    3 of 27\r\n\r\n                ', '0:11', '27:09'], ['20', '1108', '\r\n\r\n                    TIMOTHY RINGERING\r\n\r\n                ', 'M', '50', 'VANCOUVER', 'WA', '8:43', '27:02', '\r\n\r\n                    16 of 78\r\n\r\n                ', 'M 40-54', '\r\n\r\n                    4 of 27\r\n\r\n                ', '0:10', '27:12'], ['21', '1118', '\r\n\r\n                    PONTUS JADERHOLM\r\n\r\n                ', 'M', '43', 'PORTLAND', 'OR', '8:45', '27:08', '\r\n\r\n                    17 of 78\r\n\r\n                ', 'M 40-54', '\r\n\r\n                    5 of 27\r\n\r\n                ', '0:13', '27:21'], ['22', '1246', '\r\n\r\n                    KERRY FLAGG\r\n\r\n                ', 'M', '', '', '', '8:45', '27:10', '\r\n\r\n                    18 of 78\r\n\r\n                ', '', '\r\n\r\n                    4 of 9\r\n\r\n                ', '0:10', '27:20'], ['23', '1244', '\r\n\r\n                    JARRED FLAGG\r\n\r\n                ', 'M', '', '', '', '8:46', '27:11', '\r\n\r\n                    19 of 78\r\n\r\n                ', '', '\r\n\r\n                    5 of 9\r\n\r\n                ', '0:10', '27:21'], ['24', '1224', '\r\n\r\n                    KEN SKEEN\r\n\r\n                ', 'M', '57', 'PORTLAND', 'OR', '8:46', '27:12', '\r\n\r\n                    20 of 78\r\n\r\n                ', 'M 55+', '\r\n\r\n                    1 of 5\r\n\r\n                ', '0:18', '27:30'], ['25', '1065', '\r\n\r\n                    SARA KOPTON\r\n\r\n                ', 'F', '40', 'PORTLAND', 'OR', '8:51', '27:27', '\r\n\r\n                    5 of 113\r\n\r\n                ', 'F 40-54', '\r\n\r\n                    3 of 37\r\n\r\n                ', '0:20', '27:47'], ['26', '1274', '\r\n\r\n                    KAISER GUEST\r\n\r\n                ', 'F', '40', 'PORTLAND', 'OR', '8:54', '27:37', '\r\n\r\n                    6 of 113\r\n\r\n                ', 'F 40-54', '\r\n\r\n                    4 of 37\r\n\r\n                ', '0:09', '27:46'], ['27', '1208', '\r\n\r\n                    JUSTIN PERZ\r\n\r\n                ', 'M', '33', 'PORTLAND', 'OR', '8:55', '27:39', '\r\n\r\n                    21 of 78\r\n\r\n                ', 'M 21-39', '\r\n\r\n                    10 of 33\r\n\r\n                ', '0:38', '28:17'], ['28', '1072', '\r\n\r\n                    ESTELA SÁNCHEZ\r\n\r\n                ', 'F', '41', 'PORTLAND', 'OR', '8:57', '27:45', '\r\n\r\n                    7 of 113\r\n\r\n                ', 'F 40-54', '\r\n\r\n                    5 of 37\r\n\r\n                ', '0:08', '27:53'], ['29', '1018', '\r\n\r\n                    JASON WILLIAMS\r\n\r\n                ', 'M', '41', 'PORTLAND', 'OR', '8:58', '27:50', '\r\n\r\n                    22 of 78\r\n\r\n                ', 'M 40-54', '\r\n\r\n                    6 of 27\r\n\r\n                ', '0:23', '28:13'], ['30', '1297', '\r\n\r\n                    ADRIANA BRITTON\r\n\r\n                ', 'F', '53', 'PORTLAND', 'OR', '9:00', '27:54', '\r\n\r\n                    8 of 113\r\n\r\n                ', 'F 40-54', '\r\n\r\n                    6 of 37\r\n\r\n                ', '0:12', '28:06'], ['31', '1117', '\r\n\r\n                    MARK WOOD\r\n\r\n                ', 'M', '43', 'PORTLAND', 'OR', '9:03', '28:05', '\r\n\r\n                    23 of 78\r\n\r\n                ', 'M 40-54', '\r\n\r\n                    7 of 27\r\n\r\n                ', '0:30', '28:35'], ['32', '1201', '\r\n\r\n                    STEVE CRANDELL\r\n\r\n                ', 'M', '61', 'PORTLAND', 'OR', '9:03', '28:06', '\r\n\r\n                    24 of 78\r\n\r\n                ', 'M 55+', '\r\n\r\n                    2 of 5\r\n\r\n                ', '0:09', '28:15'], ['33', '1110', '\r\n\r\n                    DARRELL KRIECHBAUM\r\n\r\n                ', 'M', '53', 'PORTLAND', 'OR', '9:05', '28:11', '\r\n\r\n                    25 of 78\r\n\r\n                ', 'M 40-54', '\r\n\r\n                    8 of 27\r\n\r\n                ', '0:12', '28:23'], ['34', '1104', '\r\n\r\n                    JANICE JACOBS\r\n\r\n                ', 'F', '55', 'SALEM', 'OR', '9:05', '28:11', '\r\n\r\n                    9 of 113\r\n\r\n                ', 'F 55+', '\r\n\r\n                    1 of 14\r\n\r\n                ', '0:15', '28:26'], ['35', '1300', '\r\n\r\n                    CORY ANDERSON\r\n\r\n                ', 'M', '30', 'PORTLAND', 'OR', '9:06', '28:14', '\r\n\r\n                    26 of 78\r\n\r\n                ', 'M 21-39', '\r\n\r\n                    11 of 33\r\n\r\n                ', '0:19', '28:33'], ['36', '1238', '\r\n\r\n                    PAUL SUMMERS\r\n\r\n                ', 'M', '24', 'PORTLAND', 'OR', '9:08', '28:21', '\r\n\r\n                    27 of 78\r\n\r\n                ', 'M 21-39', '\r\n\r\n                    12 of 33\r\n\r\n                ', '0:15', '28:36'], ['37', '1298', '\r\n\r\n                    ALEX NGUYEN\r\n\r\n                ', 'M', '26', '', '', '9:09', '28:22', '\r\n\r\n                    28 of 78\r\n\r\n                ', 'M 21-39', '\r\n\r\n                    13 of 33\r\n\r\n                ', '0:19', '28:41'], ['38', '1157', '\r\n\r\n                    JEREMY SWEET\r\n\r\n                ', 'M', '27', 'PORTLAND', 'OR', '9:12', '28:32', '\r\n\r\n                    29 of 78\r\n\r\n                ', 'M 21-39', '\r\n\r\n                    14 of 33\r\n\r\n                ', '0:20', '28:52'], ['39', '1106', '\r\n\r\n                    DANIEL JOHNSTON\r\n\r\n                ', 'M', '43', 'PORTLAND', 'OR', '9:12', '28:32', '\r\n\r\n                    30 of 78\r\n\r\n                ', 'M 40-54', '\r\n\r\n                    9 of 27\r\n\r\n                ', '0:12', '28:44'], ['40', '1196', '\r\n\r\n                    LIZANN DUNEGAN\r\n\r\n                ', 'F', '53', 'PORTLAND', 'OR', '9:13', '28:34', '\r\n\r\n                    10 of 113\r\n\r\n                ', 'F 40-54', '\r\n\r\n                    7 of 37\r\n\r\n                ', '0:14', '28:48'], ['41', '1239', '\r\n\r\n                    ALYX WYNN\r\n\r\n                ', 'F', '28', 'PORTLAND', 'OR', '9:14', '28:37', '\r\n\r\n                    11 of 113\r\n\r\n                ', 'F 21-39', '\r\n\r\n                    3 of 53\r\n\r\n                ', '0:21', '28:58'], ['42', '1087', '\r\n\r\n                    YALOUNDA HUNT\r\n\r\n                ', 'F', '60', 'PORTLAND', 'OR', '9:14', '28:40', '\r\n\r\n                    12 of 113\r\n\r\n                ', 'F 55+', '\r\n\r\n                    2 of 14\r\n\r\n                ', '0:09', '28:49'], ['43', '1068', '\r\n\r\n                    SERGIO RIVERA\r\n\r\n                ', 'M', '32', 'PORTLAND', 'OR', '9:15', '28:41', '\r\n\r\n                    31 of 78\r\n\r\n                ', 'M 21-39', '\r\n\r\n                    15 of 33\r\n\r\n                ', '0:21', '29:02'], ['44', '1071', '\r\n\r\n                    PEDRO FLORES\r\n\r\n                ', 'M', '42', 'PORTLAND', 'OR', '9:15', '28:42', '\r\n\r\n                    32 of 78\r\n\r\n                ', 'M 40-54', '\r\n\r\n                    10 of 27\r\n\r\n                ', '0:08', '28:50'], ['45', '1159', '\r\n\r\n                    JEFF DOWNEY\r\n\r\n                ', 'M', '36', 'PORTLAND', 'OR', '9:15', '28:42', '\r\n\r\n                    33 of 78\r\n\r\n                ', 'M 21-39', '\r\n\r\n                    16 of 33\r\n\r\n                ', '0:19', '29:01'], ['46', '1241', '\r\n\r\n                    NICK SCHUDER\r\n\r\n                ', 'M', '44', 'PORTLAND', 'OR', '9:16', '28:45', '\r\n\r\n                    34 of 78\r\n\r\n                ', 'M 40-54', '\r\n\r\n                    11 of 27\r\n\r\n                ', '0:18', '29:03'], ['47', '1023', '\r\n\r\n                    JOHN GARDNER\r\n\r\n                ', 'M', '44', 'PORTLAND', 'OR', '9:18', '28:51', '\r\n\r\n                    35 of 78\r\n\r\n                ', 'M 40-54', '\r\n\r\n                    12 of 27\r\n\r\n                ', '0:25', '29:16'], ['48', '1253', '\r\n\r\n                    JAZMIN BEMBRY\r\n\r\n                ', 'F', '23', 'PORTLAND', 'OR', '9:20', '28:56', '\r\n\r\n                    13 of 113\r\n\r\n                ', 'F 21-39', '\r\n\r\n                    4 of 53\r\n\r\n                ', '0:15', '29:11'], ['49', '1247', '\r\n\r\n                    THEO KINWAN\r\n\r\n                ', 'F', '', '', '', '9:24', '29:09', '\r\n\r\n                    14 of 113\r\n\r\n                ', '', '\r\n\r\n                    6 of 9\r\n\r\n                ', '0:10', '29:19'], ['50', '1019', '\r\n\r\n                    ERIKA TURNEY\r\n\r\n                ', 'F', '46', 'BATTLE GROUNDB', 'WA', '9:24', '29:10', '\r\n\r\n                    15 of 113\r\n\r\n                ', 'F 40-54', '\r\n\r\n                    8 of 37\r\n\r\n                ', '0:24', '29:34'], ['51', '1066', '\r\n\r\n                    MICHELLE FRAZIER\r\n\r\n                ', 'F', '27', 'PORTLAND', 'OR', '9:25', '29:12', '\r\n\r\n                    16 of 113\r\n\r\n                ', 'F 21-39', '\r\n\r\n                    5 of 53\r\n\r\n                ', '0:13', '29:25'], ['52', '1151', '\r\n\r\n                    CHRISTINA LECHER\r\n\r\n                ', 'F', '31', 'MILWAUKEE', 'WI', '9:28', '29:21', '\r\n\r\n                    17 of 113\r\n\r\n                ', 'F 21-39', '\r\n\r\n                    6 of 53\r\n\r\n                ', '0:18', '29:39'], ['53', '1152', '\r\n\r\n                    BERNARD RAHMING\r\n\r\n                ', 'M', '31', 'PORTLAND', 'OR', '9:28', '29:21', '\r\n\r\n                    36 of 78\r\n\r\n                ', 'M 21-39', '\r\n\r\n                    17 of 33\r\n\r\n                ', '0:18', '29:39'], ['54', '1095', '\r\n\r\n                    TROY PICKARD\r\n\r\n                ', 'M', '36', 'PORTLAND', 'OR', '9:28', '29:22', '\r\n\r\n                    37 of 78\r\n\r\n                ', 'M 21-39', '\r\n\r\n                    18 of 33\r\n\r\n                ', '0:44', '30:06'], ['55', '1028', '\r\n\r\n                    JONATHAN TILLMAN\r\n\r\n                ', 'M', '49', 'PORTLAND', 'OR', '9:28', '29:23', '\r\n\r\n                    38 of 78\r\n\r\n                ', 'M 40-54', '\r\n\r\n                    13 of 27\r\n\r\n                ', '0:24', '29:47'], ['56', '1174', '\r\n\r\n                    CYNJAYSHA BOLES\r\n\r\n                ', 'F', '26', 'PORTLAND', 'OR', '9:36', '29:46', '\r\n\r\n                    18 of 113\r\n\r\n                ', 'F 21-39', '\r\n\r\n                    7 of 53\r\n\r\n                ', '0:09', '29:55'], ['57', '1013', '\r\n\r\n                    TERESA MCGRATH\r\n\r\n                ', 'F', '65', 'PORTLAND', 'OR', '9:37', '29:51', '\r\n\r\n                    19 of 113\r\n\r\n                ', 'F 55+', '\r\n\r\n                    3 of 14\r\n\r\n                ', '0:10', '30:01'], ['58', '1237', '\r\n\r\n                    ERYN HOERSTER\r\n\r\n                ', 'F', '37', 'PORTLAND', 'OR', '9:53', '30:41', '\r\n\r\n                    20 of 113\r\n\r\n                ', 'F 21-39', '\r\n\r\n                    8 of 53\r\n\r\n                ', '0:40', '31:21'], ['59', '1230', '\r\n\r\n                    EDUARDO ARIZAGA\r\n\r\n                ', 'M', '38', 'PORTLAND', 'OR', '9:58', '30:55', '\r\n\r\n                    39 of 78\r\n\r\n                ', 'M 21-39', '\r\n\r\n                    19 of 33\r\n\r\n                ', '0:47', '31:42'], ['60', '1236', '\r\n\r\n                    BEN HOERSTER\r\n\r\n                ', 'M', '37', 'PORTLAND', 'OR', '10:09', '31:29', '\r\n\r\n                    40 of 78\r\n\r\n                ', 'M 21-39', '\r\n\r\n                    20 of 33\r\n\r\n                ', '0:43', '32:12'], ['61', '1125', '\r\n\r\n                    ABIGAIL VAN GELDER\r\n\r\n                ', 'F', '36', 'PORTLAND', 'OR', '10:12', '31:37', '\r\n\r\n                    21 of 113\r\n\r\n                ', 'F 21-39', '\r\n\r\n                    9 of 53\r\n\r\n                ', '0:16', '31:53'], ['62', '1053', '\r\n\r\n                    DAMIANA KING\r\n\r\n                ', 'F', '38', 'PORTLAND', 'OR', '10:20', '32:02', '\r\n\r\n                    22 of 113\r\n\r\n                ', 'F 21-39', '\r\n\r\n                    10 of 53\r\n\r\n                ', '0:12', '32:14'], ['63', '1010', '\r\n\r\n                    HEATHER CERMAK\r\n\r\n                ', 'F', '29', 'PORTLAND', 'OR', '10:23', '32:11', '\r\n\r\n                    23 of 113\r\n\r\n                ', 'F 21-39', '\r\n\r\n                    11 of 53\r\n\r\n                ', '0:41', '32:52'], ['64', '1011', '\r\n\r\n                    COLE CHRIST\r\n\r\n                ', 'M', '19', 'PORTLAND', 'OR', '10:23', '32:11', '\r\n\r\n                    41 of 78\r\n\r\n                ', 'M 20 and Under', '\r\n\r\n                    1 of 7\r\n\r\n                ', '0:42', '32:53'], ['65', '1179', '\r\n\r\n                    MIRIAN HINOJOSA\r\n\r\n                ', 'F', '40', 'MILWAUKIE', 'OR', '10:34', '32:48', '\r\n\r\n                    24 of 113\r\n\r\n                ', 'F 40-54', '\r\n\r\n                    9 of 37\r\n\r\n                ', '0:14', '33:02'], ['66', '1183', '\r\n\r\n                    CAMERON SEIDLING\r\n\r\n                ', 'M', '28', 'PORTLAND', 'OR', '10:44', '33:16', '\r\n\r\n                    42 of 78\r\n\r\n                ', 'M 21-39', '\r\n\r\n                    21 of 33\r\n\r\n                ', '0:37', '33:53'], ['67', '1137', '\r\n\r\n                    LARRY JENKINS\r\n\r\n                ', 'M', '31', 'PORTLAND', 'OR', '10:44', '33:16', '\r\n\r\n                    43 of 78\r\n\r\n                ', 'M 21-39', '\r\n\r\n                    22 of 33\r\n\r\n                ', '0:34', '33:50'], ['68', '1173', '\r\n\r\n                    ALYS MEYER\r\n\r\n                ', 'F', '12', 'PORTLAND', 'OR', '10:49', '33:33', '\r\n\r\n                    25 of 113\r\n\r\n                ', 'F 20 and Under', '\r\n\r\n                    1 of 6\r\n\r\n                ', '0:27', '34:00'], ['69', '1103', '\r\n\r\n                    SARAH MEYER\r\n\r\n                ', 'F', '34', 'PORTLAND', 'OR', '10:50', '33:36', '\r\n\r\n                    26 of 113\r\n\r\n                ', 'F 21-39', '\r\n\r\n                    12 of 53\r\n\r\n                ', '0:26', '34:02'], ['70', '1100', '\r\n\r\n                    ELIZABETH TAYLOR\r\n\r\n                ', 'F', '39', 'PORTLAND', 'OR', '10:51', '33:40', '\r\n\r\n                    27 of 113\r\n\r\n                ', 'F 21-39', '\r\n\r\n                    13 of 53\r\n\r\n                '

In [17]:

df = pd.DataFrame(data)
print(df)

             0     1                                                  2   \
0    Finishers:   191                                               None
1         Male:    78                                               None
2       Female:   113                                               None
3          None  None                                               None
4             1  1191  \r\n\r\n                    MAX RANDOLPH\r\n\r...
..          ...   ...                                                ...
190         187  1254  \r\n\r\n                    CYNTHIA HARRIS\r\n...
191         188  1085  \r\n\r\n                    EBONY LAWRENCE\r\n...
192         189  1170  \r\n\r\n                    ANTHONY WILLIAMS\r...
193         190  2087  \r\n\r\n                    LEESHA POSEY\r\n\r...
194         191  1216  \r\n\r\n                    ZULMA OCHOA\r\n\r\...

       3     4           5     6      7        8   \
0    None  None        None  None   None     None
1    None  None        None  None   None     None
2    None  None        None  None   None     None
3    None  None        None  None   None     None
4       M    29  WASHINGTON    DC   5:25    16:48
..    ...   ...         ...   ...    ...      ...
190     F    64    PORTLAND    OR  21:53  1:07:51
191     F    30    PORTLAND    OR  22:00  1:08:12
192     M    39    PORTLAND    OR  22:19  1:09:11
193     F    43    PORTLAND    OR  30:17  1:33:53
194     F    40     GRESHAM    OR  33:22  1:43:27

                                                    9        10  \
0                                                 None     None
1                                                 None     None
2                                                 None     None
3                                                 None     None
4    \r\n\r\n                    1 of 78\r\n\r\n   ...  M 21-39
..                                                 ...      ...
190  \r\n\r\n                    110 of 113\r\n\r\n...    F 55+
191  \r\n\r\n                    111 of 113\r\n\r\n...  F 21-39
192  \r\n\r\n                    78 of 78\r\n\r\n  ...  M 21-39
193  \r\n\r\n                    112 of 113\r\n\r\n...  F 40-54
194  \r\n\r\n                    113 of 113\r\n\r\n...  F 40-54

                                                    11    12       13
0                                                 None  None     None
1                                                 None  None     None
2                                                 None  None     None
3                                                 None  None     None
4    \r\n\r\n                    1 of 33\r\n\r\n   ...  0:08    16:56
..                                                 ...   ...      ...
190  \r\n\r\n                    14 of 14\r\n\r\n  ...  1:19  1:09:10
191  \r\n\r\n                    53 of 53\r\n\r\n  ...  0:58  1:09:10
192  \r\n\r\n                    33 of 33\r\n\r\n  ...  0:08  1:09:19
193  \r\n\r\n                    36 of 37\r\n\r\n  ...  0:00  1:33:53
194  \r\n\r\n                    37 of 37\r\n\r\n  ...  0:00  1:43:27

[195 rows x 14 columns]

In [18]:

df = pd.DataFrame(data)
print(df.head(2))

           0    1     2     3     4     5     6     7     8     9     10  \
0  Finishers:  191  None  None  None  None  None  None  None  None  None
1       Male:   78  None  None  None  None  None  None  None  None  None

     11    12    13
0  None  None  None
1  None  None  None

In [19]:

df = pd.DataFrame(data)
print(df.tail(2))

      0     1                                                  2  3   4   \
193  190  2087  \r\n\r\n                    LEESHA POSEY\r\n\r...  F  43
194  191  1216  \r\n\r\n                    ZULMA OCHOA\r\n\r\...  F  40

           5   6      7        8   \
193  PORTLAND  OR  30:17  1:33:53
194   GRESHAM  OR  33:22  1:43:27

                                                    9        10  \
193  \r\n\r\n                    112 of 113\r\n\r\n...  F 40-54
194  \r\n\r\n                    113 of 113\r\n\r\n...  F 40-54

                                                    11    12       13
193  \r\n\r\n                    36 of 37\r\n\r\n  ...  0:00  1:33:53
194  \r\n\r\n                    37 of 37\r\n\r\n  ...  0:00  1:43:27

In [20]:
col_headers = soup.find_all("th")
col_headers

[<th>Place</th>,
 <th>Bib</th>,
 <th>Name</th>,
 <th>Gender</th>,
 <th>Age</th>,
 <th>City</th>,
 <th>State</th>,
 <th>Chip Pace</th>,
 <th>Time</th>,
 <th>Gender Place</th>,
 <th>Age Group</th>,
 <th>Age Group Place</th>,
 <th>Time to Start</th>,
 <th>Gun Time</th>]

In [21]:
col_rows = soup.find_all("tr")
col_rows

[<tr colspan="2">
 <b>5K:</b>
 </tr>,
 <tr>
 <td>Finishers:</td>
 <td>191</td>
 </tr>,
 <tr>
 <td>Male:</td>
 <td>78</td>
 </tr>,
 <tr>
 <td>Female:</td>
 <td>113</td>
 </tr>,
 <tr class="header">
 <th>Place</th>
 <th>Bib</th>
 <th>Name</th>
 <th>Gender</th>
 <th>Age</th>
 <th>City</th>
 <th>State</th>
 <th>Chip Pace</th>
 <th>Time</th>
 <th>Gender Place</th>
 <th>Age Group</th>
 <th>Age Group Place</th>
 <th>Time to Start</th>
 <th>Gun Time</th>
 </tr>,
 <tr data-bib="1191">
 <td>1</td>
 <td>1191</td>
 <td>

                     MAX RANDOLPH

                 </td>
 <td>M</td>
 <td>29</td>
 <td>WASHINGTON</td>
 <td>DC</td>
 <td>5:25</td>
 <td>16:48</td>
 <td>

                     1 of 78

                 </td>
 <td>M 21-39</td>
 <td>

                     1 of 33

                 </td>
 <td>0:08</td>
 <td>16:56</td>
 </tr>,
 <tr data-bib="1080">
 <td>2</td>
 <td>1080</td>
 <td>

                     NEED NAME KAISER RUNNER

                 </td>
 <td>M</td>
 <td>25</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>5:39</td>
 <td>17:31</td>
 <td>

                     2 of 78

                 </td>
 <td>M 21-39</td>
 <td>

                     2 of 33

                 </td>
 <td>0:09</td>
 <td>17:40</td>
 </tr>,
 <tr data-bib="1275">
 <td>3</td>
 <td>1275</td>
 <td>

                     DAN FRANEK

                 </td>
 <td>M</td>
 <td>52</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>5:53</td>
 <td>18:15</td>
 <td>

                     3 of 78

                 </td>
 <td>M 40-54</td>
 <td>

                     1 of 27

                 </td>
 <td>0:07</td>
 <td>18:22</td>
 </tr>,
 <tr data-bib="1223">
 <td>4</td>
 <td>1223</td>
 <td>

                     PAUL TAYLOR

                 </td>
 <td>M</td>
 <td>54</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>5:58</td>
 <td>18:31</td>
 <td>

                     4 of 78

                 </td>
 <td>M 40-54</td>
 <td>

                     2 of 27

                 </td>
 <td>0:07</td>
 <td>18:38</td>
 </tr>,
 <tr data-bib="1245">
 <td>5</td>
 <td>1245</td>
 <td>

                     THEO KINMAN

                 </td>
 <td>M</td>
 <td>22</td>
 <td></td>
 <td></td>
 <td>6:17</td>
 <td>19:31</td>
 <td>

                     5 of 78

                 </td>
 <td>M 21-39</td>
 <td>

                     3 of 33

                 </td>
 <td>0:09</td>
 <td>19:40</td>
 </tr>,
 <tr data-bib="1185">
 <td>6</td>
 <td>1185</td>
 <td>

                     MELISSA GIRGIS

                 </td>
 <td>F</td>
 <td>27</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>6:20</td>
 <td>19:39</td>
 <td>

                     1 of 113

                 </td>
 <td>F 21-39</td>
 <td>

                     1 of 53

                 </td>
 <td>0:07</td>
 <td>19:46</td>
 </tr>,
 <tr data-bib="1251">
 <td>7</td>
 <td>1251</td>
 <td>

                     CHARLIE COGGESHALL

                 </td>
 <td>M</td>
 <td>39</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>6:24</td>
 <td>19:51</td>
 <td>

                     6 of 78

                 </td>
 <td>M 21-39</td>
 <td>

                     4 of 33

                 </td>
 <td>0:10</td>
 <td>20:01</td>
 </tr>,
 <tr data-bib="1154">
 <td>8</td>
 <td>1154</td>
 <td>

                     UNKNOWN RUNNER SEE TIMER

                 </td>
 <td>M</td>
 <td></td>
 <td></td>
 <td></td>
 <td>8:03</td>
 <td>24:58</td>
 <td>

                     7 of 78

                 </td>
 <td></td>
 <td>

                     1 of 9

                 </td>
 <td>2:00</td>
 <td>26:58</td>
 </tr>,
 <tr data-bib="1163">
 <td>9</td>
 <td>1163</td>
 <td>

                     UNKNOWN RUNNER SEE TIMER

                 </td>
 <td>M</td>
 <td></td>
 <td></td>
 <td></td>
 <td>8:04</td>
 <td>25:01</td>
 <td>

                     8 of 78

                 </td>
 <td></td>
 <td>

                     2 of 9

                 </td>
 <td>1:59</td>
 <td>27:00</td>
 </tr>,
 <tr data-bib="1242">
 <td>10</td>
 <td>1242</td>
 <td>

                     KIMONTI WILSON

                 </td>
 <td>F</td>
 <td>48</td>
 <td></td>
 <td></td>
 <td>8:04</td>
 <td>25:01</td>
 <td>

                     2 of 113

                 </td>
 <td>F 40-54</td>
 <td>

                     1 of 37

                 </td>
 <td>1:59</td>
 <td>27:00</td>
 </tr>,
 <tr data-bib="1017">
 <td>11</td>
 <td>1017</td>
 <td>

                     COREY MCMANUS

                 </td>
 <td>M</td>
 <td>37</td>
 <td>BEAVERTON</td>
 <td>OR</td>
 <td>8:09</td>
 <td>25:17</td>
 <td>

                     9 of 78

                 </td>
 <td>M 21-39</td>
 <td>

                     5 of 33

                 </td>
 <td>0:22</td>
 <td>25:39</td>
 </tr>,
 <tr data-bib="1112">
 <td>12</td>
 <td>1112</td>
 <td>

                     MITCHELL JOHNSON

                 </td>
 <td>M</td>
 <td>25</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>8:13</td>
 <td>25:31</td>
 <td>

                     10 of 78

                 </td>
 <td>M 21-39</td>
 <td>

                     6 of 33

                 </td>
 <td>0:15</td>
 <td>25:46</td>
 </tr>,
 <tr data-bib="1062">
 <td>13</td>
 <td>1062</td>
 <td>

                     ALEX KABA

                 </td>
 <td>M</td>
 <td>36</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>8:14</td>
 <td>25:31</td>
 <td>

                     11 of 78

                 </td>
 <td>M 21-39</td>
 <td>

                     7 of 33

                 </td>
 <td>0:14</td>
 <td>25:45</td>
 </tr>,
 <tr data-bib="1227">
 <td>14</td>
 <td>1227</td>
 <td>

                     ROBYN MCGILLIS

                 </td>
 <td>F</td>
 <td>44</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>8:18</td>
 <td>25:44</td>
 <td>

                     3 of 113

                 </td>
 <td>F 40-54</td>
 <td>

                     2 of 37

                 </td>
 <td>0:08</td>
 <td>25:52</td>
 </tr>,
 <tr data-bib="1067">
 <td>15</td>
 <td>1067</td>
 <td>

                     MITCHELL WARDEN

                 </td>
 <td>M</td>
 <td>29</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>8:19</td>
 <td>25:46</td>
 <td>

                     12 of 78

                 </td>
 <td>M 21-39</td>
 <td>

                     8 of 33

                 </td>
 <td>0:14</td>
 <td>26:00</td>
 </tr>,
 <tr data-bib="1136">
 <td>16</td>
 <td>1136</td>
 <td>

                     JULIA METZ

                 </td>
 <td>F</td>
 <td>32</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>8:33</td>
 <td>26:31</td>
 <td>

                     4 of 113

                 </td>
 <td>F 21-39</td>
 <td>

                     2 of 53

                 </td>
 <td>0:33</td>
 <td>27:04</td>
 </tr>,
 <tr data-bib="1199">
 <td>17</td>
 <td>1199</td>
 <td>

                     JEREMY AREZZINI

                 </td>
 <td>M</td>
 <td>38</td>
 <td>LAKE OSWEGO</td>
 <td>OR</td>
 <td>8:37</td>
 <td>26:44</td>
 <td>

                     13 of 78

                 </td>
 <td>M 21-39</td>
 <td>

                     9 of 33

                 </td>
 <td>0:41</td>
 <td>27:25</td>
 </tr>,
 <tr data-bib="1252">
 <td>18</td>
 <td>1252</td>
 <td>

                     ETHAN POWELL

                 </td>
 <td>M</td>
 <td></td>
 <td></td>
 <td></td>
 <td>8:40</td>
 <td>26:52</td>
 <td>

                     14 of 78

                 </td>
 <td></td>
 <td>

                     3 of 9

                 </td>
 <td>0:11</td>
 <td>27:03</td>
 </tr>,
 <tr data-bib="1231">
 <td>19</td>
 <td>1231</td>
 <td>

                     TIMOTHY KEARNEY

                 </td>
 <td>M</td>
 <td>42</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>8:42</td>
 <td>26:58</td>
 <td>

                     15 of 78

                 </td>
 <td>M 40-54</td>
 <td>

                     3 of 27

                 </td>
 <td>0:11</td>
 <td>27:09</td>
 </tr>,
 <tr data-bib="1108">
 <td>20</td>
 <td>1108</td>
 <td>

                     TIMOTHY RINGERING

                 </td>
 <td>M</td>
 <td>50</td>
 <td>VANCOUVER</td>
 <td>WA</td>
 <td>8:43</td>
 <td>27:02</td>
 <td>

                     16 of 78

                 </td>
 <td>M 40-54</td>
 <td>

                     4 of 27

                 </td>
 <td>0:10</td>
 <td>27:12</td>
 </tr>,
 <tr data-bib="1118">
 <td>21</td>
 <td>1118</td>
 <td>

                     PONTUS JADERHOLM

                 </td>
 <td>M</td>
 <td>43</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>8:45</td>
 <td>27:08</td>
 <td>

                     17 of 78

                 </td>
 <td>M 40-54</td>
 <td>

                     5 of 27

                 </td>
 <td>0:13</td>
 <td>27:21</td>
 </tr>,
 <tr data-bib="1246">
 <td>22</td>
 <td>1246</td>
 <td>

                     KERRY FLAGG

                 </td>
 <td>M</td>
 <td></td>
 <td></td>
 <td></td>
 <td>8:45</td>
 <td>27:10</td>
 <td>

                     18 of 78

                 </td>
 <td></td>
 <td>

                     4 of 9

                 </td>
 <td>0:10</td>
 <td>27:20</td>
 </tr>,
 <tr data-bib="1244">
 <td>23</td>
 <td>1244</td>
 <td>

                     JARRED FLAGG

                 </td>
 <td>M</td>
 <td></td>
 <td></td>
 <td></td>
 <td>8:46</td>
 <td>27:11</td>
 <td>

                     19 of 78

                 </td>
 <td></td>
 <td>

                     5 of 9

                 </td>
 <td>0:10</td>
 <td>27:21</td>
 </tr>,
 <tr data-bib="1224">
 <td>24</td>
 <td>1224</td>
 <td>

                     KEN SKEEN

                 </td>
 <td>M</td>
 <td>57</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>8:46</td>
 <td>27:12</td>
 <td>

                     20 of 78

                 </td>
 <td>M 55+</td>
 <td>

                     1 of 5

                 </td>
 <td>0:18</td>
 <td>27:30</td>
 </tr>,
 <tr data-bib="1065">
 <td>25</td>
 <td>1065</td>
 <td>

                     SARA KOPTON

                 </td>
 <td>F</td>
 <td>40</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>8:51</td>
 <td>27:27</td>
 <td>

                     5 of 113

                 </td>
 <td>F 40-54</td>
 <td>

                     3 of 37

                 </td>
 <td>0:20</td>
 <td>27:47</td>
 </tr>,
 <tr data-bib="1274">
 <td>26</td>
 <td>1274</td>
 <td>

                     KAISER GUEST

                 </td>
 <td>F</td>
 <td>40</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>8:54</td>
 <td>27:37</td>
 <td>

                     6 of 113

                 </td>
 <td>F 40-54</td>
 <td>

                     4 of 37

                 </td>
 <td>0:09</td>
 <td>27:46</td>
 </tr>,
 <tr data-bib="1208">
 <td>27</td>
 <td>1208</td>
 <td>

                     JUSTIN PERZ

                 </td>
 <td>M</td>
 <td>33</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>8:55</td>
 <td>27:39</td>
 <td>

                     21 of 78

                 </td>
 <td>M 21-39</td>
 <td>

                     10 of 33

                 </td>
 <td>0:38</td>
 <td>28:17</td>
 </tr>,
 <tr data-bib="1072">
 <td>28</td>
 <td>1072</td>
 <td>

                     ESTELA SÁNCHEZ

                 </td>
 <td>F</td>
 <td>41</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>8:57</td>
 <td>27:45</td>
 <td>

                     7 of 113

                 </td>
 <td>F 40-54</td>
 <td>

                     5 of 37

                 </td>
 <td>0:08</td>
 <td>27:53</td>
 </tr>,
 <tr data-bib="1018">
 <td>29</td>
 <td>1018</td>
 <td>

                     JASON WILLIAMS

                 </td>
 <td>M</td>
 <td>41</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>8:58</td>
 <td>27:50</td>
 <td>

                     22 of 78

                 </td>
 <td>M 40-54</td>
 <td>

                     6 of 27

                 </td>
 <td>0:23</td>
 <td>28:13</td>
 </tr>,
 <tr data-bib="1297">
 <td>30</td>
 <td>1297</td>
 <td>

                     ADRIANA BRITTON

                 </td>
 <td>F</td>
 <td>53</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>9:00</td>
 <td>27:54</td>
 <td>

                     8 of 113

                 </td>
 <td>F 40-54</td>
 <td>

                     6 of 37

                 </td>
 <td>0:12</td>
 <td>28:06</td>
 </tr>,
 <tr data-bib="1117">
 <td>31</td>
 <td>1117</td>
 <td>

                     MARK WOOD

                 </td>
 <td>M</td>
 <td>43</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>9:03</td>
 <td>28:05</td>
 <td>

                     23 of 78

                 </td>
 <td>M 40-54</td>
 <td>

                     7 of 27

                 </td>
 <td>0:30</td>
 <td>28:35</td>
 </tr>,
 <tr data-bib="1201">
 <td>32</td>
 <td>1201</td>
 <td>

                     STEVE CRANDELL

                 </td>
 <td>M</td>
 <td>61</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>9:03</td>
 <td>28:06</td>
 <td>

                     24 of 78

                 </td>
 <td>M 55+</td>
 <td>

                     2 of 5

                 </td>
 <td>0:09</td>
 <td>28:15</td>
 </tr>,
 <tr data-bib="1110">
 <td>33</td>
 <td>1110</td>
 <td>

                     DARRELL KRIECHBAUM

                 </td>
 <td>M</td>
 <td>53</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>9:05</td>
 <td>28:11</td>
 <td>

                     25 of 78

                 </td>
 <td>M 40-54</td>
 <td>

                     8 of 27

                 </td>
 <td>0:12</td>
 <td>28:23</td>
 </tr>,
 <tr data-bib="1104">
 <td>34</td>
 <td>1104</td>
 <td>

                     JANICE JACOBS

                 </td>
 <td>F</td>
 <td>55</td>
 <td>SALEM</td>
 <td>OR</td>
 <td>9:05</td>
 <td>28:11</td>
 <td>

                     9 of 113

                 </td>
 <td>F 55+</td>
 <td>

                     1 of 14

                 </td>
 <td>0:15</td>
 <td>28:26</td>
 </tr>,
 <tr data-bib="1300">
 <td>35</td>
 <td>1300</td>
 <td>

                     CORY ANDERSON

                 </td>
 <td>M</td>
 <td>30</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>9:06</td>
 <td>28:14</td>
 <td>

                     26 of 78

                 </td>
 <td>M 21-39</td>
 <td>

                     11 of 33

                 </td>
 <td>0:19</td>
 <td>28:33</td>
 </tr>,
 <tr data-bib="1238">
 <td>36</td>
 <td>1238</td>
 <td>

                     PAUL SUMMERS

                 </td>
 <td>M</td>
 <td>24</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>9:08</td>
 <td>28:21</td>
 <td>

                     27 of 78

                 </td>
 <td>M 21-39</td>
 <td>

                     12 of 33

                 </td>
 <td>0:15</td>
 <td>28:36</td>
 </tr>,
 <tr data-bib="1298">
 <td>37</td>
 <td>1298</td>
 <td>

                     ALEX NGUYEN

                 </td>
 <td>M</td>
 <td>26</td>
 <td></td>
 <td></td>
 <td>9:09</td>
 <td>28:22</td>
 <td>

                     28 of 78

                 </td>
 <td>M 21-39</td>
 <td>

                     13 of 33

                 </td>
 <td>0:19</td>
 <td>28:41</td>
 </tr>,
 <tr data-bib="1157">
 <td>38</td>
 <td>1157</td>
 <td>

                     JEREMY SWEET

                 </td>
 <td>M</td>
 <td>27</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>9:12</td>
 <td>28:32</td>
 <td>

                     29 of 78

                 </td>
 <td>M 21-39</td>
 <td>

                     14 of 33

                 </td>
 <td>0:20</td>
 <td>28:52</td>
 </tr>,
 <tr data-bib="1106">
 <td>39</td>
 <td>1106</td>
 <td>

                     DANIEL JOHNSTON

                 </td>
 <td>M</td>
 <td>43</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>9:12</td>
 <td>28:32</td>
 <td>

                     30 of 78

                 </td>
 <td>M 40-54</td>
 <td>

                     9 of 27

                 </td>
 <td>0:12</td>
 <td>28:44</td>
 </tr>,
 <tr data-bib="1196">
 <td>40</td>
 <td>1196</td>
 <td>

                     LIZANN DUNEGAN

                 </td>
 <td>F</td>
 <td>53</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>9:13</td>
 <td>28:34</td>
 <td>

                     10 of 113

                 </td>
 <td>F 40-54</td>
 <td>

                     7 of 37

                 </td>
 <td>0:14</td>
 <td>28:48</td>
 </tr>,
 <tr data-bib="1239">
 <td>41</td>
 <td>1239</td>
 <td>

                     ALYX WYNN

                 </td>
 <td>F</td>
 <td>28</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>9:14</td>
 <td>28:37</td>
 <td>

                     11 of 113

                 </td>
 <td>F 21-39</td>
 <td>

                     3 of 53

                 </td>
 <td>0:21</td>
 <td>28:58</td>
 </tr>,
 <tr data-bib="1087">
 <td>42</td>
 <td>1087</td>
 <td>

                     YALOUNDA HUNT

                 </td>
 <td>F</td>
 <td>60</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>9:14</td>
 <td>28:40</td>
 <td>

                     12 of 113

                 </td>
 <td>F 55+</td>
 <td>

                     2 of 14

                 </td>
 <td>0:09</td>
 <td>28:49</td>
 </tr>,
 <tr data-bib="1068">
 <td>43</td>
 <td>1068</td>
 <td>

                     SERGIO RIVERA

                 </td>
 <td>M</td>
 <td>32</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>9:15</td>
 <td>28:41</td>
 <td>

                     31 of 78

                 </td>
 <td>M 21-39</td>
 <td>

                     15 of 33

                 </td>
 <td>0:21</td>
 <td>29:02</td>
 </tr>,
 <tr data-bib="1071">
 <td>44</td>
 <td>1071</td>
 <td>

                     PEDRO FLORES

                 </td>
 <td>M</td>
 <td>42</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>9:15</td>
 <td>28:42</td>
 <td>

                     32 of 78

                 </td>
 <td>M 40-54</td>
 <td>

                     10 of 27

                 </td>
 <td>0:08</td>
 <td>28:50</td>
 </tr>,
 <tr data-bib="1159">
 <td>45</td>
 <td>1159</td>
 <td>

                     JEFF DOWNEY

                 </td>
 <td>M</td>
 <td>36</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>9:15</td>
 <td>28:42</td>
 <td>

                     33 of 78

                 </td>
 <td>M 21-39</td>
 <td>

                     16 of 33

                 </td>
 <td>0:19</td>
 <td>29:01</td>
 </tr>,
 <tr data-bib="1241">
 <td>46</td>
 <td>1241</td>
 <td>

                     NICK SCHUDER

                 </td>
 <td>M</td>
 <td>44</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>9:16</td>
 <td>28:45</td>
 <td>

                     34 of 78

                 </td>
 <td>M 40-54</td>
 <td>

                     11 of 27

                 </td>
 <td>0:18</td>
 <td>29:03</td>
 </tr>,
 <tr data-bib="1023">
 <td>47</td>
 <td>1023</td>
 <td>

                     JOHN GARDNER

                 </td>
 <td>M</td>
 <td>44</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>9:18</td>
 <td>28:51</td>
 <td>

                     35 of 78

                 </td>
 <td>M 40-54</td>
 <td>

                     12 of 27

                 </td>
 <td>0:25</td>
 <td>29:16</td>
 </tr>,
 <tr data-bib="1253">
 <td>48</td>
 <td>1253</td>
 <td>

                     JAZMIN BEMBRY

                 </td>
 <td>F</td>
 <td>23</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>9:20</td>
 <td>28:56</td>
 <td>

                     13 of 113

                 </td>
 <td>F 21-39</td>
 <td>

                     4 of 53

                 </td>
 <td>0:15</td>
 <td>29:11</td>
 </tr>,
 <tr data-bib="1247">
 <td>49</td>
 <td>1247</td>
 <td>

                     THEO KINWAN

                 </td>
 <td>F</td>
 <td></td>
 <td></td>
 <td></td>
 <td>9:24</td>
 <td>29:09</td>
 <td>

                     14 of 113

                 </td>
 <td></td>
 <td>

                     6 of 9

                 </td>
 <td>0:10</td>
 <td>29:19</td>
 </tr>,
 <tr data-bib="1019">
 <td>50</td>
 <td>1019</td>
 <td>

                     ERIKA TURNEY

                 </td>
 <td>F</td>
 <td>46</td>
 <td>BATTLE GROUNDB</td>
 <td>WA</td>
 <td>9:24</td>
 <td>29:10</td>
 <td>

                     15 of 113

                 </td>
 <td>F 40-54</td>
 <td>

                     8 of 37

                 </td>
 <td>0:24</td>
 <td>29:34</td>
 </tr>,
 <tr data-bib="1066">
 <td>51</td>
 <td>1066</td>
 <td>

                     MICHELLE FRAZIER

                 </td>
 <td>F</td>
 <td>27</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>9:25</td>
 <td>29:12</td>
 <td>

                     16 of 113

                 </td>
 <td>F 21-39</td>
 <td>

                     5 of 53

                 </td>
 <td>0:13</td>
 <td>29:25</td>
 </tr>,
 <tr data-bib="1151">
 <td>52</td>
 <td>1151</td>
 <td>

                     CHRISTINA LECHER

                 </td>
 <td>F</td>
 <td>31</td>
 <td>MILWAUKEE</td>
 <td>WI</td>

In [22]:
header_list = []
col_header = soup.find_all("th")
for col in col_header:
    header_list.append(col.text)
print(header_list)

['Place', 'Bib', 'Name', 'Gender', 'Age', 'City', 'State', 'Chip Pace', 'Time', 'Gender Place', 'Age Group', 'Age Group Place', 'Time to Start', 'Gun Time']

In [23]:
df.columns = header_list
print(df.head())

        Place   Bib                                               Name Gender  \
0  Finishers:   191                                               None   None
1       Male:    78                                               None   None
2     Female:   113                                               None   None
3        None  None                                               None   None
4           1  1191  \r\n\r\n                    MAX RANDOLPH\r\n\r...      M

    Age        City State Chip Pace   Time  \
0  None        None  None      None   None
1  None        None  None      None   None
2  None        None  None      None   None
3  None        None  None      None   None
4    29  WASHINGTON    DC      5:25  16:48

                                        Gender Place Age Group  \
0                                               None      None
1                                               None      None
2                                               None      None
3                                               None      None
4  \r\n\r\n                    1 of 78\r\n\r\n   ...   M 21-39

                                     Age Group Place Time to Start Gun Time
0                                               None          None     None
1                                               None          None     None
2                                               None          None     None
3                                               None          None     None
4  \r\n\r\n                    1 of 33\r\n\r\n   ...          0:08    16:56

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Place            194 non-null    object
 1   Bib              194 non-null    object
 2   Name             191 non-null    object
 3   Gender           191 non-null    object
 4   Age              191 non-null    object
 5   City             191 non-null    object
 6   State            191 non-null    object
 7   Chip Pace        191 non-null    object
 8   Time             191 non-null    object
 9   Gender Place     191 non-null    object
 10  Age Group        191 non-null    object
 11  Age Group Place  191 non-null    object
 12  Time to Start    191 non-null    object
 13  Gun Time         191 non-null    object
dtypes: object(14)
memory usage: 21.5+ KB

In [25]:
df.shape

(195, 14)

In [26]:
df2 = df.dropna(how = "any")
df2.shape

(191, 14)

In [30]:
df2["ChipTime_minutes"] = pd.to_timedelta(df2["Chip Time"])
df2["ChipTime_minutes"] = df2["ChipTime_minutes"].astype("timedelta64[s]") /60
print(df2[["Gender", "ChipTime_minutes"]].tail())

KeyError: 'Chip Time'

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Place            194 non-null    object
 1   Bib              194 non-null    object
 2   Name             191 non-null    object
 3   Gender           191 non-null    object
 4   Age              191 non-null    object
 5   City             191 non-null    object
 6   State            191 non-null    object
 7   Chip Pace        191 non-null    object
 8   Time             191 non-null    object
 9   Gender Place     191 non-null    object
 10  Age Group        191 non-null    object
 11  Age Group Place  191 non-null    object
 12  Time to Start    191 non-null    object
 13  Gun Time         191 non-null    object
dtypes: object(14)
memory usage: 21.5+ KB